"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'true').strip().lower() == 'true'

SECRET_KEY = os.environ.get('SECRET_KEY', '').strip()
if not SECRET_KEY and DEBUG:
    SECRET_KEY = 'django-insecure-local-development-only'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'manniu_auth.apps.ManniuAuthConfig',
    'api_gateway.apps.ApiGatewayConfig',
    'core',
    'traditional_valuation',
    'predictive_valuation',
    'stock_selection',
    'backtest_engine',
    'financials',
    'market_data',
    'market_sentiment',
    'indices',
    'ops_logging.apps.OpsLoggingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'api_gateway.middleware.RequestContextMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
REQUIRED_POSTGRES_SETTINGS = (
    'DB_ENGINE',
    'DB_NAME',
    'DB_USER',
    'DB_PASSWORD',
    'DB_HOST',
    'DB_PORT',
)
missing_postgres_settings = [
    setting for setting in REQUIRED_POSTGRES_SETTINGS if not os.environ.get(setting)
]
if missing_postgres_settings:
    missing_names = ', '.join(missing_postgres_settings)
    raise RuntimeError(f'Missing required PostgreSQL settings: {missing_names}')

if os.environ['DB_ENGINE'] != 'django.db.backends.postgresql':
    raise RuntimeError('DB_ENGINE must be django.db.backends.postgresql')

TUSHARE_TOKEN = os.environ.get('TUSHARE_TOKEN', '')
PREDICTIVE_VALUATION_ENABLED = os.environ.get('PREDICTIVE_VALUATION_ENABLED', 'false').strip().lower() == 'true'
PREDICTIVE_VALUATION_CONFIG = os.environ.get(
    'PREDICTIVE_VALUATION_CONFIG',
    'predictive_valuation/configs/default.yaml',
).strip()
PREDICTIVE_VALUATION_MODEL_ROOT = os.environ.get(
    'PREDICTIVE_VALUATION_MODEL_ROOT',
    'predictive_valuation/outputs',
).strip()
PREDICTIVE_VALUATION_RISK_DATA_ROOT = os.environ.get(
    'PREDICTIVE_VALUATION_RISK_DATA_ROOT',
    'predictive_valuation/outputs_risk',
).strip()
PREDICTIVE_VALUATION_LOOKBACK_YEARS = int(os.environ.get('PREDICTIVE_VALUATION_LOOKBACK_YEARS', '5'))
PREDICTIVE_VALUATION_EVENT_DEBOUNCE_SECONDS = int(
    os.environ.get('PREDICTIVE_VALUATION_EVENT_DEBOUNCE_SECONDS', '900')
)
PREDICTIVE_VALUATION_MAX_FEATURE_GAP_DAYS = int(
    os.environ.get('PREDICTIVE_VALUATION_MAX_FEATURE_GAP_DAYS', '5')
)
PREDICTIVE_VALUATION_STRICT_LIVE_FEATURES = (
    os.environ.get('PREDICTIVE_VALUATION_STRICT_LIVE_FEATURES', 'true').strip().lower() == 'true'
)

AUTH_ACCESS_TOKEN_TTL_SECONDS = int(os.environ.get('AUTH_ACCESS_TOKEN_TTL_SECONDS', '900'))
AUTH_REFRESH_TOKEN_TTL_SECONDS = int(os.environ.get('AUTH_REFRESH_TOKEN_TTL_SECONDS', '2592000'))
AUTH_LOGIN_MAX_FAILURES = int(os.environ.get('AUTH_LOGIN_MAX_FAILURES', '5'))
AUTH_LOGIN_LOCK_SECONDS = int(os.environ.get('AUTH_LOGIN_LOCK_SECONDS', '900'))
AUTH_TOKEN_HASH_SECRET = os.environ.get('AUTH_TOKEN_HASH_SECRET', '').strip()
AUTH_COOKIE_SECURE = os.environ.get('AUTH_COOKIE_SECURE', 'true').strip().lower() == 'true'
AUTH_ALLOWED_CORS_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('AUTH_ALLOWED_CORS_ORIGINS', '').split(',')
    if origin.strip()
]
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'false').strip().lower() == 'true'
SESSION_COOKIE_SECURE = AUTH_COOKIE_SECURE
CSRF_COOKIE_SECURE = AUTH_COOKIE_SECURE

DATABASES = {
    'default': {
        'ENGINE': os.environ['DB_ENGINE'],
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


OPS_DB_LOG_ENABLED = os.environ.get('OPS_DB_LOG_ENABLED', 'true').strip().lower() == 'true'
OPS_DB_LOG_LEVEL = os.environ.get('OPS_DB_LOG_LEVEL', 'INFO').strip().upper()
OPS_DB_LOG_QUEUE_SIZE = int(os.environ.get('OPS_DB_LOG_QUEUE_SIZE', '2000'))
OPS_DB_LOG_BATCH_SIZE = int(os.environ.get('OPS_DB_LOG_BATCH_SIZE', '100'))
OPS_DB_LOG_FLUSH_SECONDS = float(os.environ.get('OPS_DB_LOG_FLUSH_SECONDS', '1.0'))
OPS_DB_LOG_MESSAGE_MAX = int(os.environ.get('OPS_DB_LOG_MESSAGE_MAX', '4000'))
OPS_DB_LOG_STACK_MAX = int(os.environ.get('OPS_DB_LOG_STACK_MAX', '16000'))
OPS_DB_LOG_RETENTION_DAYS = int(os.environ.get('OPS_DB_LOG_RETENTION_DAYS', '30'))
OPS_DB_ERROR_RETENTION_DAYS = int(os.environ.get('OPS_DB_ERROR_RETENTION_DAYS', '90'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
