# Generated by Django 5.2.14 on 2026-09-13 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0006_citic_business_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_quantity', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_cost', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_currency', models.CharField(default='CNY', max_length=3)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('as_of_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='personal_user.holdingportfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holding_positions', to='market_data.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=32)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurityListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('WATCHLIST', 'Watchlist'), ('OBSERVATION', 'Observation')], max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_list_items', to='market_data.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_list_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='holdingportfolio',
            index=models.Index(fields=['user', 'archived_at', 'sort_order'], name='pu_port_user_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingportfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='pu_port_user_name_uq'),
        ),
        migrations.AddIndex(
            model_name='holdingposition',
            index=models.Index(fields=['user', 'portfolio'], name='pu_pos_user_port_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingposition',
            constraint=models.UniqueConstraint(fields=('portfolio', 'security'), name='pu_pos_port_sec_uq'),
        ),
        migrations.AddConstraint(
            model_name='holdingposition',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__lte', models.F('quantity'))), name='pu_pos_avail_lte_qty'),
        ),
        migrations.AddIndex(
            model_name='usersecuritylistitem',
            index=models.Index(fields=['user', 'list_type', 'sort_order'], name='pu_list_user_type_ord_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersecuritylistitem',
            constraint=models.UniqueConstraint(fields=('user', 'security', 'list_type'), name='pu_list_user_sec_type_uq'),
        ),
    ]
