feature_tech:
# - corporation
- ts_code
- trade_date
# - freq
- open_pre_close_change
- open_pre_close_pct_chg
- change
- pct_change
- pct_vol_chg
- vol_status_ma6
- vol_status_ma10
- vol_status_ma16
- vol_status_ma25
- vol_status_ma43
- vol_status_ma60
- vol_status_ma90
- vol_status_ma120
- vol_status_ma200
- vol_30d_10pct_diff
- vol_30d_25pct_diff
- vol_30d_50pct_diff
- vol_30d_75pct_diff
- vol_30d_90pct_diff
- vol_60d_10pct_diff
- vol_60d_25pct_diff
- vol_60d_50pct_diff
- vol_60d_75pct_diff
- vol_60d_90pct_diff
- vol_90d_10pct_diff
- vol_90d_25pct_diff
- vol_90d_50pct_diff
- vol_90d_75pct_diff
- vol_90d_90pct_diff
- vol_120d_10pct_diff
- vol_120d_25pct_diff
- vol_120d_50pct_diff
- vol_120d_75pct_diff
- vol_120d_90pct_diff
- vol_200d_10pct_diff
- vol_200d_25pct_diff
- vol_200d_50pct_diff
- vol_200d_75pct_diff
- vol_200d_90pct_diff
- amount_30d_10pct_diff
- amount_30d_25pct_diff
- amount_30d_50pct_diff
- amount_30d_75pct_diff
- amount_30d_90pct_diff
- amount_60d_10pct_diff
- amount_60d_25pct_diff
- amount_60d_50pct_diff
- amount_60d_75pct_diff
- amount_60d_90pct_diff
- amount_90d_10pct_diff
- amount_90d_25pct_diff
- amount_90d_50pct_diff
- amount_90d_75pct_diff
- amount_90d_90pct_diff
- amount_120d_10pct_diff
- amount_120d_25pct_diff
- amount_120d_50pct_diff
- amount_120d_75pct_diff
- amount_120d_90pct_diff
- amount_200d_10pct_diff
- amount_200d_25pct_diff
- amount_200d_50pct_diff
- amount_200d_75pct_diff
- amount_200d_90pct_diff
- close_qfq_30d_10pct_diff
- close_qfq_30d_25pct_diff
- close_qfq_30d_50pct_diff
- close_qfq_30d_75pct_diff
- close_qfq_30d_90pct_diff
- close_qfq_60d_10pct_diff
- close_qfq_60d_25pct_diff
- close_qfq_60d_50pct_diff
- close_qfq_60d_75pct_diff
- close_qfq_60d_90pct_diff
- close_qfq_90d_10pct_diff
- close_qfq_90d_25pct_diff
- close_qfq_90d_50pct_diff
- close_qfq_90d_75pct_diff
- close_qfq_90d_90pct_diff
- close_qfq_120d_10pct_diff
- close_qfq_120d_25pct_diff
- close_qfq_120d_50pct_diff
- close_qfq_120d_75pct_diff
- close_qfq_120d_90pct_diff
- close_qfq_200d_10pct_diff
- close_qfq_200d_25pct_diff
- close_qfq_200d_50pct_diff
- close_qfq_200d_75pct_diff
- close_qfq_200d_90pct_diff
- close_ma6_diff
- high_ma6_diff
- low_ma6_diff
- close_ma10_diff
- high_ma10_diff
- low_ma10_diff
- close_ma16_diff
- high_ma16_diff
- low_ma16_diff
- close_ma25_diff
- high_ma25_diff
- low_ma25_diff
- close_ma43_diff
- high_ma43_diff
- low_ma43_diff
- close_ma60_diff
- high_ma60_diff
- low_ma60_diff
- close_ma90_diff
- high_ma90_diff
- low_ma90_diff
- close_ma120_diff
- high_ma120_diff
- low_ma120_diff
- close_ma200_diff
- high_ma200_diff
- low_ma200_diff
- ma6_ma10_entangled
- ma6_ma10_ma25_entangled
- ma6_ma10_ma25_ma60_entangled
- ma6_ma10_ma25_ma60_ma120_ma200_entangled
- ma6_trend
- ma10_trend
- ma16_trend
- ma25_trend
- ma43_trend
- ma60_trend
- ma90_trend
- ma120_trend
- ma200_trend
- atr_6
- atr_10
- atr_14
- atr_20
- atr_25
- close_atr_6_upper_diff
- high_atr_6_upper_diff
- low_atr_6_upper_diff
- close_atr_10_upper_diff
- high_atr_10_upper_diff
- low_atr_10_upper_diff
- close_atr_14_upper_diff
- high_atr_14_upper_diff
- low_atr_14_upper_diff
- close_atr_20_upper_diff
- high_atr_20_upper_diff
- low_atr_20_upper_diff
- close_atr_25_upper_diff
- high_atr_25_upper_diff
- low_atr_25_upper_diff
- close_atr_6_x2_upper_diff
- high_atr_6_x2_upper_diff
- low_atr_6_x2_upper_diff
- close_atr_10_x2_upper_diff
- high_atr_10_x2_upper_diff
- low_atr_10_x2_upper_diff
- close_atr_14_x2_upper_diff
- high_atr_14_x2_upper_diff
- low_atr_14_x2_upper_diff
- close_atr_20_x2_upper_diff
- high_atr_20_x2_upper_diff
- low_atr_20_x2_upper_diff
- close_atr_25_x2_upper_diff
- high_atr_25_x2_upper_diff
- low_atr_25_x2_upper_diff
- close_atr_6_lower_diff
- high_atr_6_lower_diff
- low_atr_6_lower_diff
- close_atr_10_lower_diff
- high_atr_10_lower_diff
- low_atr_10_lower_diff
- close_atr_14_lower_diff
- high_atr_14_lower_diff
- low_atr_14_lower_diff
- close_atr_20_lower_diff
- high_atr_20_lower_diff
- low_atr_20_lower_diff
- close_atr_25_lower_diff
- high_atr_25_lower_diff
- low_atr_25_lower_diff
- close_atr_6_x2_lower_diff
- high_atr_6_x2_lower_diff
- low_atr_6_x2_lower_diff
- close_atr_10_x2_lower_diff
- high_atr_10_x2_lower_diff
- low_atr_10_x2_lower_diff
- close_atr_14_x2_lower_diff
- high_atr_14_x2_lower_diff
- low_atr_14_x2_lower_diff
- close_atr_20_x2_lower_diff
- high_atr_20_x2_lower_diff
- low_atr_20_x2_lower_diff
- close_atr_25_x2_lower_diff
- high_atr_25_x2_lower_diff
- low_atr_25_x2_lower_diff
- volatility_ratio_6
- volatility_ratio_10
- volatility_ratio_14
- volatility_ratio_20
- volatility_ratio_25
- macd_dif
- macd_dea
- macd
- kdj_k
- kdj_d
- kdj_j
- rsi_6
- rsi_12
- rsi_24
- high_boll_upper_diff
- close_boll_upper_diff
- low_boll_upper_diff
- high_boll_mid_diff
- close_boll_mid_diff
- low_boll_mid_diff
- high_boll_lower_diff
- close_boll_lower_diff
- low_boll_lower_diff
- cci
- is_bullish_and_divergent
- is_bearish_and_divergent
- is_t_shape
- is_lower_shadow_shape
- is_upper_shadow_shape
- is_double_top

feature_fundamental:
# - corporation
- ts_code
- trade_date
- freq
- turnover_rate
- turnover_rate_f
- turnover_rate_f_30d_10pct_diff
- turnover_rate_f_30d_25pct_diff
- turnover_rate_f_30d_50pct_diff
- turnover_rate_f_30d_75pct_diff
- turnover_rate_f_30d_90pct_diff
- turnover_rate_f_60d_10pct_diff
- turnover_rate_f_60d_25pct_diff
- turnover_rate_f_60d_50pct_diff
- turnover_rate_f_60d_75pct_diff
- turnover_rate_f_60d_90pct_diff
- turnover_rate_f_90d_10pct_diff
- turnover_rate_f_90d_25pct_diff
- turnover_rate_f_90d_50pct_diff
- turnover_rate_f_90d_75pct_diff
- turnover_rate_f_90d_90pct_diff
- turnover_rate_f_120d_10pct_diff
- turnover_rate_f_120d_25pct_diff
- turnover_rate_f_120d_50pct_diff
- turnover_rate_f_120d_75pct_diff
- turnover_rate_f_120d_90pct_diff
- turnover_rate_f_200d_10pct_diff
- turnover_rate_f_200d_25pct_diff
- turnover_rate_f_200d_50pct_diff
- turnover_rate_f_200d_75pct_diff
- turnover_rate_f_200d_90pct_diff
- volume_ratio
- volume_ratio_30d_10pct_diff
- volume_ratio_30d_25pct_diff
- volume_ratio_30d_50pct_diff
- volume_ratio_30d_75pct_diff
- volume_ratio_30d_90pct_diff
- volume_ratio_60d_10pct_diff
- volume_ratio_60d_25pct_diff
- volume_ratio_60d_50pct_diff
- volume_ratio_60d_75pct_diff
- volume_ratio_60d_90pct_diff
- volume_ratio_90d_10pct_diff
- volume_ratio_90d_25pct_diff
- volume_ratio_90d_50pct_diff
- volume_ratio_90d_75pct_diff
- volume_ratio_90d_90pct_diff
- volume_ratio_120d_10pct_diff
- volume_ratio_120d_25pct_diff
- volume_ratio_120d_50pct_diff
- volume_ratio_120d_75pct_diff
- volume_ratio_120d_90pct_diff
- volume_ratio_200d_10pct_diff
- volume_ratio_200d_25pct_diff
- volume_ratio_200d_50pct_diff
- volume_ratio_200d_75pct_diff
- volume_ratio_200d_90pct_diff
- pe
- pe_30d_10pct_diff
- pe_30d_25pct_diff
- pe_30d_50pct_diff
- pe_30d_75pct_diff
- pe_30d_90pct_diff
- pe_60d_10pct_diff
- pe_60d_25pct_diff
- pe_60d_50pct_diff
- pe_60d_75pct_diff
- pe_60d_90pct_diff
- pe_90d_10pct_diff
- pe_90d_25pct_diff
- pe_90d_50pct_diff
- pe_90d_75pct_diff
- pe_90d_90pct_diff
- pe_120d_10pct_diff
- pe_120d_25pct_diff
- pe_120d_50pct_diff
- pe_120d_75pct_diff
- pe_120d_90pct_diff
- pe_200d_10pct_diff
- pe_200d_25pct_diff
- pe_200d_50pct_diff
- pe_200d_75pct_diff
- pe_200d_90pct_diff
- pe_ttm
- pb
- pb_30d_10pct_diff
- pb_30d_25pct_diff
- pb_30d_50pct_diff
- pb_30d_75pct_diff
- pb_30d_90pct_diff
- pb_60d_10pct_diff
- pb_60d_25pct_diff
- pb_60d_50pct_diff
- pb_60d_75pct_diff
- pb_60d_90pct_diff
- pb_90d_10pct_diff
- pb_90d_25pct_diff
- pb_90d_50pct_diff
- pb_90d_75pct_diff
- pb_90d_90pct_diff
- pb_120d_10pct_diff
- pb_120d_25pct_diff
- pb_120d_50pct_diff
- pb_120d_75pct_diff
- pb_120d_90pct_diff
- pb_200d_10pct_diff
- pb_200d_25pct_diff
- pb_200d_50pct_diff
- pb_200d_75pct_diff
- pb_200d_90pct_diff
- ps
- ps_30d_10pct_diff
- ps_30d_25pct_diff
- ps_30d_50pct_diff
- ps_30d_75pct_diff
- ps_30d_90pct_diff
- ps_60d_10pct_diff
- ps_60d_25pct_diff
- ps_60d_50pct_diff
- ps_60d_75pct_diff
- ps_60d_90pct_diff
- ps_90d_10pct_diff
- ps_90d_25pct_diff
- ps_90d_50pct_diff
- ps_90d_75pct_diff
- ps_90d_90pct_diff
- ps_120d_10pct_diff
- ps_120d_25pct_diff
- ps_120d_50pct_diff
- ps_120d_75pct_diff
- ps_120d_90pct_diff
- ps_200d_10pct_diff
- ps_200d_25pct_diff
- ps_200d_50pct_diff
- ps_200d_75pct_diff
- ps_200d_90pct_diff
- ps_ttm
- dv_ratio
- dv_ttm
- total_share
- float_share
- free_share
- total_mv
- circ_mv

feature_cost:
# - corporation
- close_his_low_diff
- close_his_high_diff
- close_cost_5pct_diff
- close_cost_15pct_diff
- close_cost_50pct_diff
- close_cost_85pct_diff
- close_cost_95pct_diff
- close_weight_avg_diff
- high_weight_avg_diff
- low_weight_avg_diff
- high_cost_5pct_diff
- high_cost_15pct_diff
- high_cost_50pct_diff
- high_cost_85pct_diff
- high_cost_95pct_diff
- low_cost_5pct_diff
- low_cost_15pct_diff
- low_cost_50pct_diff
- low_cost_85pct_diff
- low_cost_95pct_diff
- winner_rate


plugin_calc_shadows:
- lower_shadow
- upper_shadow
- body
- shadow_ratio
- pct_o2c