# Generated by Django 5.2.14 on 2026-09-07 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_security_area_security_industry_and_more'),
        ('predictive_valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveValuationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=64, unique=True)),
                ('command', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'predictive_valuation_run',
                'indexes': [models.Index(fields=['status', '-created_at'], name='pv_run_status_created')],
            },
        ),
        migrations.CreateModel(
            name='PredictiveValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asof_date', models.DateField(db_index=True)),
                ('horizon', models.CharField(default='1M', max_length=16)),
                ('model_version', models.CharField(db_index=True, max_length=128)),
                ('feature_contract_version', models.CharField(max_length=64)),
                ('artifact_hash', models.CharField(blank=True, max_length=64)),
                ('source_market_date', models.DateField(blank=True, null=True)),
                ('financial_end_date', models.DateField(blank=True, null=True)),
                ('financial_ann_date', models.DateField(blank=True, null=True)),
                ('financial_source_as_of_date', models.DateField(blank=True, null=True)),
                ('financial_report_type', models.CharField(blank=True, max_length=16)),
                ('feature_data_source', models.CharField(blank=True, max_length=32)),
                ('market_regime', models.CharField(blank=True, max_length=32)),
                ('security_regime', models.CharField(blank=True, max_length=32)),
                ('trigger_type', models.CharField(default='MANUAL', max_length=32)),
                ('signal_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('up_probability', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('target_return_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('target_return_low_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('target_return_high_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('target_price_low', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('target_price_high', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('target_market_cap', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('risk_level', models.CharField(default='MEDIUM', max_length=16)),
                ('explain', models.JSONField(blank=True, default=dict)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_valuation_snapshots', to='market_data.security')),
            ],
            options={
                'db_table': 'predictive_valuation_snapshot',
            },
        ),
        migrations.CreateModel(
            name='PredictiveValuationCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(default='1M', max_length=16)),
                ('model_version', models.CharField(db_index=True, max_length=128)),
                ('asof_date', models.DateField(db_index=True)),
                ('signal_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('target_return_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('risk_level', models.CharField(default='MEDIUM', max_length=16)),
                ('market_regime', models.CharField(blank=True, max_length=32)),
                ('security_regime', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_predictive_valuations', to='market_data.security')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='predictive_valuation.predictivevaluationsnapshot')),
            ],
            options={
                'db_table': 'predictive_valuation_current',
            },
        ),
        migrations.CreateModel(
            name='PredictiveValuationEventState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('asof_date', models.DateField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictive_valuation_events', to='market_data.security')),
            ],
            options={
                'db_table': 'predictive_valuation_event_state',
                'indexes': [models.Index(fields=['status', 'event_type', 'created_at'], name='pv_event_status_type_ct')],
            },
        ),
        migrations.AddIndex(
            model_name='predictivevaluationsnapshot',
            index=models.Index(fields=['security', '-asof_date'], name='pv_snapshot_sec_asof'),
        ),
        migrations.AddIndex(
            model_name='predictivevaluationsnapshot',
            index=models.Index(fields=['model_version', '-created_at'], name='pv_snapshot_model_ct'),
        ),
        migrations.AddConstraint(
            model_name='predictivevaluationsnapshot',
            constraint=models.UniqueConstraint(fields=('security', 'asof_date', 'horizon', 'model_version', 'feature_contract_version'), name='pv_snapshot_uniq'),
        ),
        migrations.AddIndex(
            model_name='predictivevaluationcurrent',
            index=models.Index(fields=['horizon', '-asof_date'], name='pv_current_horizon_dt'),
        ),
        migrations.AddConstraint(
            model_name='predictivevaluationcurrent',
            constraint=models.UniqueConstraint(fields=('security', 'horizon', 'model_version'), name='pv_current_uniq'),
        ),
    ]
