# Generated by Django 5.2.14 on 2026-09-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive_valuation', '0002_predictivevaluationrun_predictivevaluationsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveValuationRegimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=32, unique=True)),
                ('regime', models.CharField(max_length=16)),
                ('asof_date', models.DateField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'predictive_valuation_regime_state',
                'indexes': [models.Index(fields=['regime', '-asof_date'], name='pv_regime_state_regime_dt')],
            },
        ),
    ]
