# Generated by Django 5.2.14 on 2026-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_security_area_security_industry_and_more'),
        ('predictive_valuation', '0003_predictivevaluationregimestate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='predictivevaluationsnapshot',
            name='pv_snapshot_uniq',
        ),
        migrations.AddConstraint(
            model_name='predictivevaluationsnapshot',
            constraint=models.UniqueConstraint(fields=('security', 'asof_date', 'financial_report_type', 'horizon', 'model_version', 'feature_contract_version'), name='pv_snapshot_uniq'),
        ),
    ]
