# Generated by Django 5.1.1 on 2026-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_citic_business_match'),
        ('predictive_valuation', '0005_predictive_persistence_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivevaluationeventstate',
            name='scope_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='predictivevaluationeventstate',
            name='source_event_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='predictivevaluationeventstate',
            name='source_system',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='predictivevaluationeventstate',
            name='source_version',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='predictivevaluationeventstate',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_event_key'), name='pv_source_event_uniq'),
        ),
    ]
