# Generated by Django 5.2.4 on 2025-09-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0004_corporation_monthly_funda_inited_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocktradinghistory',
            unique_together={('trade_date', 'ts_code', 'freq')},
        ),
    ]
