# Generated by Django 5.2.4 on 2025-09-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0005_alter_stocktradinghistory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockfundamentalhistory',
            unique_together={('ts_code', 'trade_date', 'freq')},
        ),
    ]
