# Generated by Django 5.2.4 on 2025-09-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0007_alter_stockfundamentalhistory_dv_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='freq',
            field=models.CharField(default='D', help_text='如 D 日线，W 周线，M 月线', max_length=10, verbose_name='周期'),
        ),
    ]
