# Generated by Django 5.2.4 on 2025-11-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0008_alter_stockfundamentalhistory_freq'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCostHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_index=True, help_text='如 000001.SZ', max_length=10, verbose_name='股票代码')),
                ('trade_date', models.DateField(db_index=True, help_text='如 2020-05-05', verbose_name='交易日期')),
                ('his_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='历史最低价')),
                ('his_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='历史最高价')),
                ('cost_5pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='5分位成本')),
                ('cost_15pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='15分位成本')),
                ('cost_50pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='50分位成本')),
                ('cost_85pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='85分位成本')),
                ('cost_95pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='95分位成本')),
                ('weight_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='加权平均成本')),
                ('winner_rate', models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=12, null=True, verbose_name='胜率')),
                ('freq', models.CharField(default='D', help_text='如 D 日线，W 周线，M 月线', max_length=5, verbose_name='周期')),
                ('is_pulled_by_client', models.BooleanField(default=False, help_text='该数据是否由客户端拉取', verbose_name='是否由客户端拉取')),
                ('corporation', models.ForeignKey(blank=True, help_text='关联的股票公司信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_history', to='datastore.corporation', verbose_name='公司')),
            ],
            options={
                'verbose_name': '股票成本历史',
                'verbose_name_plural': '股票成本历史',
                'ordering': ['-trade_date'],
                'unique_together': {('ts_code', 'trade_date')},
            },
        ),
    ]
