# Generated by Django 5.2.4 on 2025-11-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0009_stockcosthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcosthistory',
            name='is_pulled_by_client',
        ),
        migrations.AddField(
            model_name='corporation',
            name='cost_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化成本数据', verbose_name='成本数据已初始化'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='monthly_cost_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化月成本数据', verbose_name='月成本数据已初始化'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='weekly_cost_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化周成本数据', verbose_name='周成本数据已初始化'),
        ),
    ]
