# Generated by Django 5.2.4 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0010_remove_stockcosthistory_is_pulled_by_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporation",
            name="sw_l3_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="申万三级行业编码，如 850325.SI",
                max_length=32,
                null=True,
                verbose_name="SW三级行业编码",
            ),
        ),
        migrations.AddField(
            model_name="corporation",
            name="sw_l3_name",
            field=models.CharField(
                blank=True,
                help_text="申万三级行业名称",
                max_length=128,
                null=True,
                verbose_name="SW三级行业名称",
            ),
        ),
    ]
