# Generated by Django 5.2.4 on 2025-08-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0003_fundamentalhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundamentalHistory',
            new_name='StockFundamentalHistory',
        ),
    ]
