# Generated by Django 5.2.4 on 2025-08-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0004_rename_fundamentalhistory_stockfundamentalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationBasic',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('ts_code', models.CharField(db_index=True, help_text='如 000001.SZ', max_length=10, unique=True, verbose_name='交易代码')),
                ('exchange', models.CharField(blank=True, help_text='如 SZSE/SHSE', max_length=10, null=True, verbose_name='交易所代码')),
                ('chairman', models.CharField(blank=True, max_length=50, null=True, verbose_name='法人代表')),
                ('manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='总经理')),
                ('secretary', models.CharField(blank=True, max_length=50, null=True, verbose_name='董秘')),
                ('reg_capital', models.DecimalField(blank=True, decimal_places=2, help_text='单位：万元', max_digits=20, null=True, verbose_name='注册资本')),
                ('setup_date', models.DateField(blank=True, null=True, verbose_name='注册日期')),
                ('introduction', models.TextField(blank=True, max_length=5000, null=True, verbose_name='介绍')),
                ('website', models.CharField(blank=True, max_length=128, null=True, verbose_name='主页')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮件')),
                ('office', models.CharField(blank=True, max_length=200, null=True, verbose_name='办公地址')),
                ('employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='员工数')),
                ('main_business', models.TextField(blank=True, max_length=5000, null=True, verbose_name='主营业务')),
                ('business_scope', models.TextField(blank=True, max_length=5000, null=True, verbose_name='经营范围')),
                ('area', models.ForeignKey(blank=True, help_text='公司注册省份', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporation_basic_area', to='stockdata.area', verbose_name='省份')),
                ('city', models.ForeignKey(blank=True, help_text='公司注册城市', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporation_basic_city', to='stockdata.city', verbose_name='城市')),
                ('corporation', models.ForeignKey(blank=True, help_text='关联的股票公司信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_info', to='stockdata.corporation', verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司基本信息',
                'verbose_name_plural': '公司基本信息',
                'ordering': ['ts_code'],
                'get_latest_by': 'id',
            },
        ),
    ]
