# Generated by Django 5.2.4 on 2025-09-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0009_alter_stocktradinghistory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockfundamentalhistory',
            unique_together={('ts_code', 'trade_date', 'freq')},
        ),
    ]
