# Generated by Django 5.2.4 on 2025-09-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0010_alter_stockfundamentalhistory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktradinghistory',
            name='pct_change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格变化%'),
        ),
        migrations.AlterField(
            model_name='stocktradinghistory',
            name='pct_change_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格变化%_hfq'),
        ),
        migrations.AlterField(
            model_name='stocktradinghistory',
            name='pct_change_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格变化%_qfq'),
        ),
    ]
