# Generated by Django 5.1.1 on 2026-09-06 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('source_name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('source_system', models.CharField(default='tushare', max_length=32)),
                ('source_version', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'source_system', 'source_version'), name='market_data_industry_source_uniq')],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=32)),
                ('mode', models.CharField(choices=[('BACKFILL', 'Backfill'), ('DAILY', 'Daily')], max_length=16)),
                ('frequency', models.CharField(blank=True, max_length=1)),
                ('scope_key', models.CharField(max_length=64)),
                ('requested_start_date', models.DateField(blank=True, null=True)),
                ('requested_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_row_count', models.PositiveBigIntegerField(default=0)),
                ('accepted_row_count', models.PositiveBigIntegerField(default=0)),
                ('upserted_row_count', models.PositiveBigIntegerField(default=0)),
                ('rejected_row_count', models.PositiveBigIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'status', '-id'], name='market_data_dataset_74a5f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='market_data.province')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceRegionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_version', models.CharField(max_length=32)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='region_mappings', to='market_data.province')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_mappings', to='market_data.region')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=16, unique=True)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index')], max_length=8)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=256)),
                ('market', models.CharField(blank=True, db_index=True, max_length=32)),
                ('exchange', models.CharField(blank=True, db_index=True, max_length=32)),
                ('list_status', models.CharField(blank=True, db_index=True, max_length=16)),
                ('list_date', models.DateField(blank=True, null=True)),
                ('delist_date', models.DateField(blank=True, null=True)),
                ('is_hs', models.CharField(blank=True, max_length=8)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_type', 'list_status'], name='market_data_asset_t_b734fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketBarLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('trade_date', models.DateField()),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pct_change', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('close_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_bars', to='market_data.security')),
            ],
        ),
        migrations.CreateModel(
            name='MarketBarDailyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pre_close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pct_change', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('adj_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('open_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('high_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('low_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pre_close_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('change_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pct_change_qfq', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('open_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('high_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('low_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pre_close_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('change_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pct_change_hfq', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bars', to='market_data.security')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman', models.CharField(blank=True, max_length=128)),
                ('manager', models.CharField(blank=True, max_length=128)),
                ('secretary', models.CharField(blank=True, max_length=128)),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('setup_date', models.DateField(blank=True, null=True)),
                ('province_name', models.CharField(blank=True, max_length=64)),
                ('city_name', models.CharField(blank=True, max_length=64)),
                ('exchange', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office', models.CharField(blank=True, max_length=256)),
                ('employees', models.PositiveIntegerField(blank=True, null=True)),
                ('main_business', models.TextField(blank=True)),
                ('business_scope', models.TextField(blank=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market_data.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market_data.province')),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='market_data.security')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=32)),
                ('scope_key', models.CharField(max_length=64)),
                ('frequency', models.CharField(blank=True, max_length=1)),
                ('last_complete_source_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('overlap_days', models.PositiveSmallIntegerField(default=3)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_complete_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_data.ingestionrun')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-updated_at'], name='market_data_status_2d3ecb_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'scope_key', 'frequency'), name='market_data_watermark_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='market_data_city_province_uniq'),
        ),
        migrations.AddConstraint(
            model_name='provinceregionmapping',
            constraint=models.UniqueConstraint(fields=('province', 'mapping_version', 'effective_from'), name='market_data_prov_region_uniq'),
        ),
        migrations.AddIndex(
            model_name='marketbarlatest',
            index=models.Index(fields=['frequency', '-trade_date'], name='market_data_frequen_e21cc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketbarlatest',
            constraint=models.UniqueConstraint(fields=('security', 'frequency'), name='market_data_latest_bar_uniq'),
        ),
        migrations.AddIndex(
            model_name='marketbardailyhistory',
            index=models.Index(fields=['security', '-trade_date'], name='market_data_securit_92874f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketbardailyhistory',
            index=models.Index(fields=['trade_date'], name='market_data_trade_d_db174f_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketbardailyhistory',
            constraint=models.UniqueConstraint(fields=('security', 'trade_date'), name='market_data_daily_bar_uniq'),
        ),
        migrations.AddConstraint(
            model_name='marketbardailyhistory',
            constraint=models.CheckConstraint(condition=models.Q(('volume__isnull', True), ('volume__gte', 0), _connector='OR'), name='market_data_daily_bar_volume_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='marketbardailyhistory',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='market_data_daily_bar_amount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['province', 'city'], name='market_data_provinc_5e8de5_idx'),
        ),
    ]
