# Generated by Django 5.1.1 on 2026-09-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCostDistributionLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('his_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('his_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_5pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_15pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_50pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_85pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_95pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('weight_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('winner_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_cost_distribution', to='market_data.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexDailyFundamentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pe_ttm', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('turnover_rate_f', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('float_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_index_fundamentals', to='market_data.security')),
            ],
            options={
                'indexes': [models.Index(fields=['security', '-trade_date'], name='market_data_securit_679e6e_idx'), models.Index(fields=['trade_date', 'security'], name='market_data_trade_d_284b48_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'trade_date'), name='market_data_index_fund_uniq')],
            },
        ),
        migrations.CreateModel(
            name='IndexDailyFundamentalLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pe_ttm', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('turnover_rate_f', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('float_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_index_fundamental', to='market_data.security')),
            ],
            options={
                'indexes': [models.Index(fields=['-trade_date'], name='market_data_trade_d_d40125_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockCostDistributionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('his_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('his_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_5pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_15pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_50pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_85pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost_95pct', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('weight_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('winner_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cost_distributions', to='market_data.security')),
            ],
            options={
                'indexes': [models.Index(fields=['security', '-trade_date'], name='market_data_securit_722fdb_idx'), models.Index(fields=['trade_date', 'security'], name='market_data_trade_d_d3592c_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'trade_date'), name='market_data_stock_cost_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StockDailyFundamentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('turnover_rate_f', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pe_ttm', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ps', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ps_ttm', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('dv_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('dv_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_share', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('float_share', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('free_share', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('total_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('circ_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_fundamentals', to='market_data.security')),
            ],
            options={
                'indexes': [models.Index(fields=['security', '-trade_date'], name='market_data_securit_44893c_idx'), models.Index(fields=['trade_date', 'security'], name='market_data_trade_d_d3fe50_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'trade_date'), name='market_data_stock_fund_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StockDailyFundamentalLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('turnover_rate_f', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pe_ttm', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ps', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ps_ttm', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('dv_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('dv_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_share', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('float_share', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('free_share', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('total_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('circ_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_daily_fundamental', to='market_data.security')),
            ],
            options={
                'indexes': [models.Index(fields=['-trade_date'], name='market_data_trade_d_6fb599_idx')],
            },
        ),
    ]
