# Generated by Django 5.1.1 on 2026-09-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_stockcostdistributionlatest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market_data.province'),
        ),
        migrations.AddField(
            model_name='security',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market_data.industry'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['area', 'industry', 'list_status'], name='market_data_area_id_6ba3cb_idx'),
        ),
    ]
