# Generated by Django 5.1.1 on 2026-09-08 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_security_area_security_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=32, unique=True)),
                ('current_regime', models.CharField(blank=True, max_length=16)),
                ('previous_regime', models.CharField(blank=True, max_length=16)),
                ('last_valid_trade_date', models.DateField(blank=True, null=True)),
                ('classifier_version', models.CharField(max_length=32)),
                ('source_version', models.CharField(blank=True, max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_data_market_regime_state',
            },
        ),
        migrations.CreateModel(
            name='MarketRegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asof_trade_date', models.DateField()),
                ('source_trade_date', models.DateField()),
                ('regime', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('classifier_version', models.CharField(max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='VALID', max_length=24)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benchmark_security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_regime_snapshots', to='market_data.security')),
            ],
            options={
                'db_table': 'market_data_market_regime_snapshot',
                'indexes': [models.Index(fields=['-asof_trade_date', 'regime'], name='market_data_market_regime_dt')],
                'constraints': [models.UniqueConstraint(fields=('benchmark_security', 'asof_trade_date', 'classifier_version'), name='market_data_market_regime_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RegimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('event_key', models.CharField(max_length=128)),
                ('source_trade_date', models.DateField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONSUMED', 'Consumed')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regime_events', to='market_data.security')),
            ],
            options={
                'db_table': 'market_data_regime_event',
                'indexes': [models.Index(fields=['status', '-created_at'], name='md_regime_evt_status'), models.Index(fields=['event_type', '-source_trade_date'], name='market_data_regime_event_type')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'event_key'), name='market_data_regime_event_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SecurityRegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asof_trade_date', models.DateField()),
                ('source_trade_date', models.DateField()),
                ('regime', models.CharField(max_length=16)),
                ('source', models.CharField(default='local_market_data', max_length=64)),
                ('classifier_version', models.CharField(max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='VALID', max_length=24)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regime_snapshots', to='market_data.security')),
            ],
            options={
                'db_table': 'market_data_security_regime_snapshot',
                'indexes': [models.Index(fields=['security', '-asof_trade_date'], name='market_data_security_regime_dt'), models.Index(fields=['regime', '-asof_trade_date'], name='md_sec_regime_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'asof_trade_date', 'classifier_version'), name='market_data_security_regime_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SecurityRegimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier_version', models.CharField(max_length=32)),
                ('current_regime', models.CharField(blank=True, max_length=16)),
                ('previous_regime', models.CharField(blank=True, max_length=16)),
                ('pending_regime', models.CharField(blank=True, max_length=16)),
                ('pending_days', models.PositiveSmallIntegerField(default=0)),
                ('last_valid_trade_date', models.DateField(blank=True, null=True)),
                ('source_version', models.CharField(blank=True, max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regime_state_rows', to='market_data.security')),
            ],
            options={
                'db_table': 'market_data_security_regime_state',
                'indexes': [models.Index(fields=['current_regime', '-updated_at'], name='market_data_security_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'classifier_version'), name='market_data_security_regime_state_uniq')],
            },
        ),
    ]
