# Generated by Django 5.1.1 on 2026-09-09 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_marketregimestate_marketregimesnapshot_regimeevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWIndustryMappingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(default='CN', max_length=8)),
                ('taxonomy', models.CharField(default='SW2021', max_length=16)),
                ('mapping_version', models.CharField(max_length=64)),
                ('source_hash', models.CharField(max_length=128)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('artifact', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_data_sw_industry_mapping_version',
                'indexes': [models.Index(fields=['market', 'taxonomy', 'is_active'], name='md_sw_mapping_active_idx'), models.Index(fields=['source_hash'], name='md_sw_mapping_hash_idx')],
                'constraints': [models.UniqueConstraint(fields=('market', 'taxonomy', 'mapping_version'), name='market_data_sw_mapping_version_uniq')],
            },
        ),
        migrations.CreateModel(
            name='IndustryRegimeRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_version', models.CharField(max_length=64)),
                ('rules_hash', models.CharField(max_length=128)),
                ('fallback_regime', models.CharField(default='balanced', max_length=32)),
                ('rules', models.JSONField(default=dict)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('mapping_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regime_rule_versions', to='market_data.swindustrymappingversion')),
            ],
            options={
                'db_table': 'market_data_industry_regime_rule_version',
                'indexes': [models.Index(fields=['mapping_version', 'is_active'], name='md_industry_rule_active_idx'), models.Index(fields=['rules_hash'], name='md_industry_rule_hash_idx')],
                'constraints': [models.UniqueConstraint(fields=('mapping_version', 'rules_version'), name='market_data_industry_rule_version_uniq')],
            },
        ),
    ]
