# Generated by Django 5.1.1 on 2026-09-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_swindustrymappingversion_industryregimeruleversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CITICIndustryDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(default='CN', max_length=8)),
                ('level', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('parent_code', models.CharField(blank=True, max_length=32)),
                ('mapping_version', models.CharField(max_length=64)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('source_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_data_citic_industry_dimension',
                'indexes': [models.Index(fields=['market', 'level', 'code'], name='md_citic_dim_lookup_idx'), models.Index(fields=['market', 'mapping_version', 'is_active'], name='md_citic_dim_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('market', 'level', 'code', 'mapping_version'), name='md_citic_dimension_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CITICIndustryMappingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(default='CN', max_length=8)),
                ('mapping_version', models.CharField(max_length=64)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('source_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('dimension_count', models.PositiveIntegerField(default=0)),
                ('membership_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_data_citic_mapping_run',
                'indexes': [models.Index(fields=['market', '-created_at'], name='md_citic_run_created_idx'), models.Index(fields=['status', '-created_at'], name='md_citic_run_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessIndustryMatchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asof_date', models.DateField()),
                ('level', models.CharField(default='L2', max_length=2)),
                ('requested_top_n', models.PositiveSmallIntegerField(default=3)),
                ('returned_count', models.PositiveSmallIntegerField(default=0)),
                ('profile_hash', models.CharField(blank=True, max_length=128)),
                ('profile_source', models.CharField(blank=True, max_length=64)),
                ('profile_updated_at', models.DateTimeField(blank=True, null=True)),
                ('mapping_version', models.CharField(blank=True, max_length=64)),
                ('rules_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='VALID', max_length=32)),
                ('degraded_reason', models.CharField(blank=True, max_length=128)),
                ('matches', models.JSONField(blank=True, default=list)),
                ('fallback', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_industry_match_snapshots', to='market_data.security')),
            ],
            options={
                'db_table': 'market_data_business_industry_match_snapshot',
                'indexes': [models.Index(fields=['security', '-asof_date'], name='md_business_match_sec_dt'), models.Index(fields=['status', '-asof_date'], name='md_business_match_status_dt')],
                'constraints': [models.UniqueConstraint(fields=('security', 'asof_date', 'level', 'requested_top_n', 'profile_hash', 'mapping_version', 'rules_version'), name='md_business_match_snapshot_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CITICSecurityIndustryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=2)),
                ('mapping_version', models.CharField(max_length=64)),
                ('in_date', models.DateField(blank=True, null=True)),
                ('out_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_memberships', to='market_data.citicindustrydimension')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citic_memberships', to='market_data.security')),
            ],
            options={
                'db_table': 'market_data_citic_security_membership',
                'indexes': [models.Index(fields=['security', 'level', 'mapping_version', 'is_current'], name='md_citic_member_lookup_idx'), models.Index(fields=['mapping_version', 'level'], name='md_citic_member_version_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'industry', 'mapping_version', 'in_date'), name='md_citic_member_uniq')],
            },
        ),
    ]
