# Generated by Django 5.2.14 on 2026-10-02 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0008_companyprofile_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='THSBoardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('exchange', models.CharField(max_length=16)),
                ('list_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('source_payload', models.JSONField(default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ths_board_catalog', to='market_data.security')),
            ],
        ),
        migrations.CreateModel(
            name='THSBoardDailyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pre_close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pct_change', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('vol', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ('float_mv', models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ('source_payload', models.JSONField(default=dict)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_history', to='market_data.thsboardcatalog')),
            ],
        ),
        migrations.CreateModel(
            name='THSBoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.CharField(max_length=8)),
                ('weight', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('in_date', models.DateField(blank=True, null=True)),
                ('out_date', models.DateField(blank=True, null=True)),
                ('source_payload', models.JSONField(default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='market_data.thsboardcatalog')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ths_board_memberships', to='market_data.security')),
            ],
        ),
        migrations.AddIndex(
            model_name='thsboardcatalog',
            index=models.Index(fields=['exchange', 'type'], name='md_ths_catalog_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='thsboarddailyhistory',
            index=models.Index(fields=['board', '-trade_date'], name='md_ths_daily_board_date_idx'),
        ),
        migrations.AddIndex(
            model_name='thsboarddailyhistory',
            index=models.Index(fields=['trade_date', 'board'], name='md_ths_daily_date_board_idx'),
        ),
        migrations.AddConstraint(
            model_name='thsboarddailyhistory',
            constraint=models.UniqueConstraint(fields=('board', 'trade_date'), name='md_ths_daily_board_date_uniq'),
        ),
        migrations.AddIndex(
            model_name='thsboardmembership',
            index=models.Index(fields=['board', 'is_new'], name='md_ths_member_current_idx'),
        ),
        migrations.AddIndex(
            model_name='thsboardmembership',
            index=models.Index(fields=['stock', 'is_new'], name='md_ths_member_stock_idx'),
        ),
        migrations.AddConstraint(
            model_name='thsboardmembership',
            constraint=models.UniqueConstraint(fields=('board', 'stock'), name='md_ths_member_board_stock_uniq'),
        ),
    ]
