# Generated by Django 5.2.4 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuation_api", "0002_companyprofile_business_scope_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("country", models.CharField(blank=True, default="中国", max_length=50)),
                ("name_pinyin", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "valuation_area",
                "unique_together": {("name", "country")},
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name_pinyin", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "valuation_industry",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("name_pinyin", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="cities", to="valuation_api.area"),
                ),
            ],
            options={
                "db_table": "valuation_city",
                "unique_together": {("name", "area")},
            },
        ),
        migrations.CreateModel(
            name="Corporation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts_code", models.CharField(db_index=True, max_length=12, unique=True)),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("fullname", models.CharField(blank=True, max_length=100, null=True)),
                ("enname", models.CharField(blank=True, max_length=100, null=True)),
                ("cnspell", models.CharField(blank=True, max_length=50, null=True)),
                ("market", models.CharField(blank=True, max_length=50, null=True)),
                ("exchange", models.CharField(blank=True, max_length=10, null=True)),
                ("curr_type", models.CharField(blank=True, max_length=10, null=True)),
                ("list_status", models.CharField(blank=True, max_length=1, null=True)),
                ("list_date", models.DateField(blank=True, null=True)),
                ("delist_date", models.DateField(blank=True, null=True)),
                ("act_name", models.CharField(blank=True, max_length=50, null=True)),
                ("act_ent_type", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="corporations",
                        to="valuation_api.area",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="corporations",
                        to="valuation_api.industry",
                    ),
                ),
            ],
            options={
                "db_table": "valuation_corporation",
            },
        ),
        migrations.CreateModel(
            name="CorporationBasic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts_code", models.CharField(db_index=True, max_length=12, unique=True)),
                ("exchange", models.CharField(blank=True, max_length=10, null=True)),
                ("chairman", models.CharField(blank=True, max_length=50, null=True)),
                ("manager", models.CharField(blank=True, max_length=50, null=True)),
                ("secretary", models.CharField(blank=True, max_length=50, null=True)),
                ("reg_capital", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("setup_date", models.DateField(blank=True, null=True)),
                ("introduction", models.TextField(blank=True, null=True)),
                ("website", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.EmailField(blank=True, max_length=128, null=True)),
                ("office", models.CharField(blank=True, max_length=200, null=True)),
                ("employees", models.PositiveIntegerField(blank=True, null=True)),
                ("main_business", models.TextField(blank=True, null=True)),
                ("business_scope", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="corporation_basic_area",
                        to="valuation_api.area",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="corporation_basic_city",
                        to="valuation_api.city",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="basic_info",
                        to="valuation_api.corporation",
                    ),
                ),
            ],
            options={
                "db_table": "valuation_corporation_basic",
            },
        ),
    ]
