# Generated by Django 5.2.4 on 2026-03-21 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_api', '0004_valuationsnapshotlatest'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockfundamentalsnapshot',
            name='valuation_f_ts_code_3f0f16_idx',
        ),
        migrations.RenameIndex(
            model_name='valuationsnapshotlatest',
            new_name='valuation_s_ts_code_c10f3a_idx',
            old_name='valuation_a_ts_code_4ae0a8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockfundamentalsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='circ_mv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamental_history', to='valuation_api.corporation'),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='dv_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='dv_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='float_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='free_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='freq',
            field=models.CharField(default='D', max_length=10),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='ps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='total_mv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='total_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='trade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='turnover_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='turnover_rate_f',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='volume_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='adj_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='boll_lower',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='boll_mid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='boll_upper',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='cci',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='change_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='change_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='close_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_history', to='valuation_api.corporation'),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='high_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='high_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='kdj_d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='kdj_j',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='kdj_k',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='low_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='low_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='macd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='macd_dea',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='macd_dif',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='open_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='open_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='pct_change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='pct_change_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='pct_change_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='pre_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='pre_close_hfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='pre_close_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='rsi_12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='rsi_24',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='rsi_6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='vol',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockfundamentalsnapshot',
            unique_together={('ts_code', 'report_date', 'freq')},
        ),
        migrations.AddIndex(
            model_name='stockfundamentalsnapshot',
            index=models.Index(fields=['ts_code', 'report_date', 'freq'], name='valuation_f_ts_code_d9803e_idx'),
        ),
    ]
