# Generated by Django 5.2.4 on 2026-03-21 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_api', '0005_remove_stockfundamentalsnapshot_valuation_f_ts_code_3f0f16_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockfundamentalsnapshot',
            name='valuation_f_ts_code_d9803e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockfundamentalsnapshot',
            unique_together={('ts_code', 'trade_date', 'freq')},
        ),
        migrations.RemoveField(
            model_name='stocktradinghistory',
            name='total_mv',
        ),
        migrations.RemoveField(
            model_name='stocktradinghistory',
            name='total_share',
        ),
        migrations.AddField(
            model_name='stockfundamentalsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockfundamentalsnapshot',
            name='pb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stockfundamentalsnapshot',
            name='pe_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stockfundamentalsnapshot',
            name='ps_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stockfundamentalsnapshot',
            name='ts_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktradinghistory',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocktradinghistory',
            name='close_qfq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocktradinghistory',
            name='freq',
            field=models.CharField(default='D', max_length=5),
        ),
        migrations.AlterField(
            model_name='stocktradinghistory',
            name='ts_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='stockfundamentalsnapshot',
            index=models.Index(fields=['ts_code', 'trade_date', 'freq'], name='valuation_f_ts_code_a4d19a_idx'),
        ),
        migrations.RemoveField(
            model_name='stockfundamentalsnapshot',
            name='dividend_per_share',
        ),
        migrations.RemoveField(
            model_name='stockfundamentalsnapshot',
            name='fcff_per_share',
        ),
        migrations.RemoveField(
            model_name='stockfundamentalsnapshot',
            name='np_yoy',
        ),
        migrations.RemoveField(
            model_name='stockfundamentalsnapshot',
            name='report_date',
        ),
    ]
