# Generated by Django 5.2.4 on 2026-03-25 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_api', '0009_valuationsnapshot_backtest_reporting_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockexpressvip',
            new_name='valuation_e_ts_code_0a8b3c_idx',
            old_name='valuation_e_ts_code_61f9ca_idx',
        ),
        migrations.RenameIndex(
            model_name='valuationsnapshot',
            new_name='valuation_s_ts_code_f17f39_idx',
            old_name='valuation_s_ts_code_6f8c9e_idx',
        ),
        migrations.AlterField(
            model_name='valuationsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
