# Generated by Django 5.2.4 on 2026-03-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("valuation_api", "0010_rename_valuation_e_ts_code_61f9ca_idx_valuation_e_ts_code_0a8b3c_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenClawWatchlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("tenant_id", models.CharField(db_index=True, default="default", max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("is_default", models.BooleanField(default=False)),
                ("feishu_webhook", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "openclaw_watchlist",
                "unique_together": {("user_id", "tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="OpenClawAlertRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("tenant_id", models.CharField(db_index=True, default="default", max_length=64)),
                ("ts_code", models.CharField(db_index=True, max_length=12)),
                ("discount_threshold_pct", models.FloatField(default=20.0)),
                ("method_dispersion_threshold_pct", models.FloatField(default=25.0)),
                ("change_threshold_pct", models.FloatField(default=10.0)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "openclaw_alert_rule",
                "unique_together": {("user_id", "tenant_id", "ts_code")},
            },
        ),
        migrations.CreateModel(
            name="OpenClawAlertState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("tenant_id", models.CharField(db_index=True, default="default", max_length=64)),
                ("ts_code", models.CharField(db_index=True, max_length=12)),
                ("last_composite_gap_pct", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "openclaw_alert_state",
                "unique_together": {("user_id", "tenant_id", "ts_code")},
            },
        ),
        migrations.CreateModel(
            name="OpenClawWatchlistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts_code", models.CharField(db_index=True, max_length=12)),
                ("note", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watchlist",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="valuation_api.openclawwatchlist"),
                ),
            ],
            options={
                "db_table": "openclaw_watchlist_item",
                "unique_together": {("watchlist", "ts_code")},
            },
        ),
        migrations.AddIndex(
            model_name="openclawwatchlist",
            index=models.Index(fields=["user_id", "tenant_id", "updated_at"], name="openclaw_wa_user_id_76d7f3_idx"),
        ),
        migrations.AddIndex(
            model_name="openclawwatchlistitem",
            index=models.Index(fields=["watchlist", "ts_code"], name="openclaw_wa_watchli_1c82e2_idx"),
        ),
        migrations.AddIndex(
            model_name="openclawalertrule",
            index=models.Index(fields=["user_id", "tenant_id", "enabled"], name="openclaw_al_user_id_f4e687_idx"),
        ),
    ]
