# Generated by Django 5.2.4 on 2026-03-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_api', '0011_openclaw_watchlist_and_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenClawUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'openclaw_user',
                'indexes': [models.Index(fields=['tenant_id', 'user_id', 'is_active'], name='openclaw_us_tenant__1d00e9_idx')],
                'unique_together': {('tenant_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='OpenClawTokenCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_hint', models.CharField(blank=True, default='', max_length=16)),
                ('scopes', models.TextField(blank=True, default='')),
                ('channel', models.CharField(blank=True, default='openclaw', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='valuation_api.openclawuser')),
            ],
            options={
                'db_table': 'openclaw_token_credential',
                'indexes': [models.Index(fields=['user', 'is_active', 'expires_at'], name='openclaw_to_user_id_ec3193_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenClawUserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=32)),
                ('channel_user_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='valuation_api.openclawuser')),
            ],
            options={
                'db_table': 'openclaw_user_identity',
                'unique_together': {('channel', 'channel_user_id')},
            },
        ),
    ]
