# Generated by Django 5.1.1 on 2026-09-08 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0003_security_area_security_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalValuationParameterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_version', models.CharField(max_length=64)),
                ('market', models.CharField(default='CN', max_length=8)),
                ('sw_level', models.CharField(default='GLOBAL', max_length=8)),
                ('sw_code', models.CharField(blank=True, max_length=32)),
                ('sw_name', models.CharField(blank=True, max_length=128)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('source_hash', models.CharField(max_length=128)),
                ('engine_compatibility', models.CharField(default='1', max_length=32)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'traditional_valuation_parameter_version',
                'indexes': [models.Index(fields=['market', 'sw_level', 'sw_code'], name='tv_param_lookup_idx'), models.Index(fields=['is_active', '-created_at'], name='tv_param_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('market', 'sw_level', 'sw_code', 'parameter_version'), name='tv_param_version_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TraditionalValuationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=64, unique=True)),
                ('command', models.CharField(max_length=32)),
                ('scope', models.CharField(blank=True, max_length=128)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('planned_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'traditional_valuation_run',
                'indexes': [models.Index(fields=['status', '-created_at'], name='tv_run_status_ct')],
            },
        ),
        migrations.CreateModel(
            name='TraditionalValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asof_date', models.DateField(db_index=True)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('report_type', models.CharField(max_length=16)),
                ('financial_end_date', models.DateField(blank=True, null=True)),
                ('financial_ann_date', models.DateField(blank=True, null=True)),
                ('profit_bucket', models.CharField(default='formal', max_length=16)),
                ('valuation_variant', models.CharField(default='default', max_length=128)),
                ('style_profile', models.CharField(default='baseline', max_length=64)),
                ('parameter_version', models.CharField(max_length=64)),
                ('parameter_source_hash', models.CharField(blank=True, max_length=128)),
                ('valuation_engine_version', models.CharField(default='1.0', max_length=32)),
                ('trigger_type', models.CharField(default='MANUAL', max_length=32)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('composite_valuation_price_raw', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('composite_valuation_price_optimized', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('conservative_valuation_price_raw', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('conservative_valuation_price_optimized', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('methods', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traditional_valuation_snapshots', to='market_data.security')),
            ],
            options={
                'db_table': 'traditional_valuation_snapshot',
            },
        ),
        migrations.CreateModel(
            name='TraditionalValuationRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_engine_version', models.CharField(default='1.5', max_length=32)),
                ('risk_score', models.DecimalField(decimal_places=4, max_digits=8)),
                ('risk_level', models.CharField(max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('factors', models.JSONField(default=dict)),
                ('adjustment', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshot', to='traditional_valuation.traditionalvaluationsnapshot')),
            ],
            options={
                'db_table': 'traditional_valuation_risk_snapshot',
            },
        ),
        migrations.CreateModel(
            name='TraditionalValuationSnapshotLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=16)),
                ('profit_bucket', models.CharField(default='formal', max_length=16)),
                ('valuation_variant', models.CharField(default='default', max_length=128)),
                ('style_profile', models.CharField(default='baseline', max_length=64)),
                ('asof_date', models.DateField(db_index=True)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('composite_valuation_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('conservative_valuation_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('parameter_version', models.CharField(max_length=64)),
                ('valuation_engine_version', models.CharField(default='1.0', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='traditional_valuation.traditionalvaluationrisksnapshot')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_traditional_valuations', to='market_data.security')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='traditional_valuation.traditionalvaluationsnapshot')),
            ],
            options={
                'db_table': 'traditional_valuation_snapshot_latest',
            },
        ),
        migrations.CreateModel(
            name='TraditionalValuationEventState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('event_key', models.CharField(max_length=128)),
                ('scope_key', models.CharField(max_length=128)),
                ('source_version', models.CharField(blank=True, max_length=128)),
                ('asof_date', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.TextField(blank=True)),
                ('coalesced_event_count', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traditional_valuation_events', to='market_data.security')),
            ],
            options={
                'db_table': 'traditional_valuation_event_state',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='tv_event_status_retry'), models.Index(fields=['scope_key', 'event_type'], name='tv_event_scope_type')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'event_key'), name='tv_event_key_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='traditionalvaluationsnapshot',
            index=models.Index(fields=['security', '-asof_date'], name='tv_snapshot_sec_dt'),
        ),
        migrations.AddIndex(
            model_name='traditionalvaluationsnapshot',
            index=models.Index(fields=['report_type', 'profit_bucket', '-asof_date'], name='tv_snapshot_report_dt'),
        ),
        migrations.AddConstraint(
            model_name='traditionalvaluationsnapshot',
            constraint=models.UniqueConstraint(fields=('security', 'asof_date', 'source_trade_date', 'report_type', 'financial_end_date', 'profit_bucket', 'valuation_variant', 'parameter_version', 'valuation_engine_version'), name='tv_snapshot_identity_uniq'),
        ),
        migrations.AddIndex(
            model_name='traditionalvaluationrisksnapshot',
            index=models.Index(fields=['risk_level', '-created_at'], name='tv_risk_level_ct'),
        ),
        migrations.AddIndex(
            model_name='traditionalvaluationsnapshotlatest',
            index=models.Index(fields=['report_type', 'profit_bucket', '-asof_date'], name='tv_latest_report_dt'),
        ),
        migrations.AddConstraint(
            model_name='traditionalvaluationsnapshotlatest',
            constraint=models.UniqueConstraint(fields=('security', 'report_type', 'profit_bucket', 'valuation_variant', 'style_profile'), name='tv_snapshot_latest_uniq'),
        ),
    ]
