# Generated by Django 5.1.1 on 2026-09-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_citic_business_match'),
        ('traditional_valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalValuationVariantSummaryLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=16)),
                ('profit_bucket', models.CharField(default='formal', max_length=16)),
                ('valuation_variant', models.CharField(default='default', max_length=128)),
                ('style_profile', models.CharField(default='baseline', max_length=64)),
                ('asof_date', models.DateField(db_index=True)),
                ('compare_group', models.CharField(blank=True, max_length=32)),
                ('industry_level', models.CharField(blank=True, max_length=8)),
                ('industry_code', models.CharField(blank=True, max_length=32)),
                ('industry_name', models.CharField(blank=True, max_length=128)),
                ('match_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('composite_valuation_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('conservative_valuation_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('method_coverage', models.PositiveSmallIntegerField(default=0)),
                ('is_active_variant', models.BooleanField(default=False)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_traditional_valuation_variant_summaries', to='market_data.security')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='traditional_valuation.traditionalvaluationsnapshot')),
            ],
            options={
                'db_table': 'traditional_valuation_variant_summary_latest',
                'indexes': [models.Index(fields=['security', 'report_type', 'profit_bucket'], name='tv_variant_summary_lookup'), models.Index(fields=['is_active_variant', '-updated_at'], name='tv_variant_summary_active')],
                'constraints': [models.UniqueConstraint(fields=('security', 'report_type', 'profit_bucket', 'valuation_variant', 'style_profile'), name='tv_variant_summary_latest_uniq')],
            },
        ),
    ]
