# Generated by Django 5.1.1 on 2026-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_citic_business_match'),
        ('traditional_valuation', '0002_variant_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='traditionalvaluationeventstate',
            name='source_event_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='traditionalvaluationeventstate',
            name='source_system',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='traditionalvaluationeventstate',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_event_key'), name='tv_source_event_uniq'),
        ),
    ]
