# Generated by Django 5.2.4 on 2026-03-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('end_date', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('ann_date', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('n_income', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('q_dt_roe', models.FloatField(blank=True, null=True)),
                ('grossprofit_margin', models.FloatField(blank=True, null=True)),
                ('netprofit_margin', models.FloatField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'earnings_financial_feature_snapshot',
                'indexes': [models.Index(fields=['end_date'], name='idx_earn_fin_feat_end'), models.Index(fields=['ann_date'], name='idx_earn_fin_feat_ann')],
            },
        ),
    ]
