# Generated by Django 5.2.4 on 2025-08-24 02:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="手机号格式: '+138 1410 6610'. 最多11位数字.", regex='^\\+?1?\\d{9,15}$')], verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True, verbose_name='性别')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('address', models.TextField(blank=True, verbose_name='详细地址')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='手机已验证')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱验证令牌')),
                ('investment_experience', models.CharField(choices=[('BEGINNER', '初学者'), ('INTERMEDIATE', '中级'), ('ADVANCED', '高级'), ('PROFESSIONAL', '专业')], default='BEGINNER', max_length=20, verbose_name='投资经验')),
                ('risk_tolerance', models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险')], default='MEDIUM', max_length=10, verbose_name='风险承受能力')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('website_url', models.URLField(blank=True, verbose_name='个人网站')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='短信通知')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='推送通知')),
                ('profile_visibility', models.CharField(choices=[('PUBLIC', '公开'), ('FRIENDS', '仅好友'), ('PRIVATE', '私密')], default='PUBLIC', max_length=10, verbose_name='资料可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ts_code', models.CharField(max_length=20, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='股票名称')),
                ('hold_a_position', models.BooleanField(default=False, verbose_name='是否持仓')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.corporation', verbose_name='关联公司')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='users.user')),
            ],
            options={
                'verbose_name': '自选股',
                'verbose_name_plural': '自选股',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_deleted'], name='users_user_is_acti_748002_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwatchlist',
            unique_together={('user', 'ts_code')},
        ),
    ]
