# Generated by Django 5.2.4 on 2025-09-14 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0008_alter_stockfundamentalhistory_freq'),
        ('users', '0002_remove_user_users_user_email_6f2530_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('tag', models.CharField(max_length=50, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_system_tag', models.BooleanField(default=False, verbose_name='是否系统标签')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='datastore.corporation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '股票标签',
                'verbose_name_plural': '股票标签',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'corporation', 'tag')},
            },
        ),
    ]
