# Generated by Django 5.2.14 on 2026-09-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialfeaturepanel',
            name='security',
        ),
        migrations.DeleteModel(
            name='FinancialFeatureLatest',
        ),
        migrations.DeleteModel(
            name='FinancialFeaturePanel',
        ),
    ]
