# Generated by Django 5.2.14 on 2026-09-07 06:25

from django.db import migrations, models


def copy_typed_raw_payload_fields(apps, schema_editor):
    numeric_value = "(raw_payload ->> '{field}') ~ '^[+-]?([0-9]+(\\.[0-9]*)?|\\.[0-9]+)([eE][+-]?[0-9]+)?$'"
    mappings = {
        'financials_balance_sheet_record': ('st_borr', 'lt_borr'),
        'financials_cashflow_record': ('n_incr_cash_cash_equ',),
        'financials_indicator_record': ('q_dt_roe', 'cash_ratio', 'ocf_to_or'),
    }
    for table, fields in mappings.items():
        for field in fields:
            schema_editor.execute(
                f'''UPDATE {table}
                SET {field} = (raw_payload ->> '{field}')::numeric
                WHERE {field} IS NULL
                  AND raw_payload ? '{field}'
                  AND {numeric_value.format(field=field)}'''
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_remove_financialfeaturepanel_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbalancesheetrecord',
            name='lt_borr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetrecord',
            name='st_borr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='financialcashflowrecord',
            name='n_incr_cash_cash_equ',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='financialindicatorrecord',
            name='cash_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialindicatorrecord',
            name='ocf_to_or',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialindicatorrecord',
            name='q_dt_roe',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.RunPython(copy_typed_raw_payload_fields, noop_reverse),
    ]
