from pathlib import Path

from django.core.management.base import BaseCommand
from django.db import connection


TABLE_RENAMES = [
    ("prediction_backtestvaluationsnapshot", "valuation_backtestvaluationsnapshot"),
    ("prediction_annualoutlooksnapshot", "valuation_annualoutlooksnapshot"),
    ("prediction_stockvaluationsnapshot", "valuation_stockvaluationsnapshot"),
    ("prediction_stockvaluationsnapshothistory", "valuation_stockvaluationsnapshothistory"),
    ("prediction_stockvaluationsnapshotlatest", "valuation_stockvaluationsnapshotlatest"),
]


class Command(BaseCommand):
    help = "Generate a safe SQL plan for renaming prediction_valuation tables to valuation_ prefix."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            type=str,
            default="output/valuation_table_rename_plan.sql",
            help="Path of generated SQL plan file.",
        )
        parser.add_argument(
            "--with-rollback",
            action="store_true",
            default=False,
            help="Append rollback SQL block at the end of output file.",
        )

    def handle(self, *args, **options):
        output_path = Path(options["output"])
        include_rollback = bool(options["with_rollback"])

        checks = []
        with connection.cursor() as cursor:
            for old_name, new_name in TABLE_RENAMES:
                cursor.execute("select to_regclass(%s)", [old_name])
                old_exists = cursor.fetchone()[0] is not None

                cursor.execute("select to_regclass(%s)", [new_name])
                new_exists = cursor.fetchone()[0] is not None

                row_count = None
                if old_exists:
                    cursor.execute(f"select count(*) from {old_name}")
                    row_count = cursor.fetchone()[0]

                checks.append(
                    {
                        "old": old_name,
                        "new": new_name,
                        "old_exists": old_exists,
                        "new_exists": new_exists,
                        "rows": row_count,
                    }
                )

        self.stdout.write(self.style.NOTICE("Table check summary:"))
        for item in checks:
            self.stdout.write(
                f"- {item['old']} -> {item['new']}: "
                f"old_exists={item['old_exists']}, new_exists={item['new_exists']}, rows={item['rows']}"
            )

        missing_old = [x for x in checks if not x["old_exists"]]
        occupied_new = [x for x in checks if x["new_exists"]]

        sql_lines = [
            "-- Generated by: manage.py plan_valuation_table_rename",
            "-- This file is review-first. It is NOT auto-executed.",
            "",
            "BEGIN;",
            "",
        ]

        if missing_old:
            sql_lines.append("-- WARNING: Some source tables do not exist. Remove/fix statements before execution.")
        if occupied_new:
            sql_lines.append("-- WARNING: Some target tables already exist. Resolve name conflicts before execution.")
        if missing_old or occupied_new:
            sql_lines.append("")

        for old_name, new_name in TABLE_RENAMES:
            sql_lines.append(f"ALTER TABLE {old_name} RENAME TO {new_name};")

        sql_lines.extend([
            "",
            "COMMIT;",
            "",
            "-- Suggested pre-check:",
            "-- 1) backup related tables",
            "-- 2) run in maintenance window",
            "-- 3) run Django check and makemigrations --check --dry-run after execution",
        ])

        if include_rollback:
            sql_lines.extend([
                "",
                "-- Rollback block (manual use):",
                "BEGIN;",
            ])
            for old_name, new_name in TABLE_RENAMES:
                sql_lines.append(f"ALTER TABLE {new_name} RENAME TO {old_name};")
            sql_lines.append("COMMIT;")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(sql_lines) + "\n", encoding="utf-8")

        self.stdout.write(self.style.SUCCESS(f"SQL plan written to: {output_path}"))
        self.stdout.write(
            self.style.WARNING("No DB rename executed. Review SQL and execute manually when ready.")
        )
