# Generated by Django 5.2.4 on 2026-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('ts_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('industry', models.CharField(blank=True, default='', max_length=128)),
                ('market', models.CharField(default='CN', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'valuation_company_profile',
            },
        ),
        migrations.CreateModel(
            name='ValuationAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=128, unique=True)),
                ('pe_target', models.FloatField(default=15.0)),
                ('pb_target', models.FloatField(default=2.0)),
                ('ps_target', models.FloatField(default=2.0)),
                ('peg_target', models.FloatField(default=1.0)),
                ('discount_rate', models.FloatField(default=0.1)),
                ('terminal_growth_rate', models.FloatField(default=0.03)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'valuation_assumption',
            },
        ),
        migrations.CreateModel(
            name='StockFundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=12)),
                ('report_date', models.DateField()),
                ('pe_ttm', models.FloatField(null=True)),
                ('pb', models.FloatField(null=True)),
                ('ps_ttm', models.FloatField(null=True)),
                ('np_yoy', models.FloatField(null=True)),
                ('fcff_per_share', models.FloatField(null=True)),
                ('dividend_per_share', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'valuation_fundamental_snapshot',
                'indexes': [models.Index(fields=['ts_code', 'report_date'], name='valuation_f_ts_code_3f0f16_idx')],
                'unique_together': {('ts_code', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='StockTradingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=12)),
                ('trade_date', models.DateField()),
                ('freq', models.CharField(default='D', max_length=4)),
                ('close', models.FloatField(null=True)),
                ('close_qfq', models.FloatField(null=True)),
                ('total_mv', models.FloatField(null=True)),
                ('total_share', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'valuation_trading_history',
                'indexes': [models.Index(fields=['ts_code', 'freq', 'trade_date'], name='valuation_t_ts_code_654133_idx')],
                'unique_together': {('ts_code', 'trade_date', 'freq')},
            },
        ),
    ]
