# Generated by Django 5.2.14 on 2026-09-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0008_companyprofile_protocol'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('FINANCIAL_HEALTH_6D', 'Financial health 6D'), ('MODEL_TOPN_6D', 'Model TopN 6D'), ('COMPANY_GROWTH_POTENTIAL', 'Company growth potential')], max_length=40)),
                ('asof_date', models.DateField()),
                ('financial_end_date', models.DateField(blank=True, null=True)),
                ('market_asof_date', models.DateField(blank=True, null=True)),
                ('report_type', models.CharField(blank=True, default='', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('score_status', models.CharField(choices=[('VALID', 'Valid'), ('PARTIAL', 'Partial'), ('INSUFFICIENT_DATA', 'Insufficient data'), ('NOT_APPLICABLE', 'Not applicable'), ('DEGRADED', 'Degraded'), ('NOT_AVAILABLE', 'Not available')], max_length=32)),
                ('coverage', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('calculation_version', models.CharField(blank=True, default='', max_length=64)),
                ('scoring_version', models.CharField(blank=True, default='', max_length=64)),
                ('profile_version', models.CharField(blank=True, default='', max_length=64)),
                ('peer_mapping_version', models.CharField(blank=True, default='', max_length=64)),
                ('model_version', models.CharField(blank=True, default='', max_length=128)),
                ('feature_set_version', models.CharField(blank=True, default='', max_length=128)),
                ('mapping_version', models.CharField(blank=True, default='', max_length=64)),
                ('normalization_version', models.CharField(blank=True, default='', max_length=64)),
                ('dimension_weight_version', models.CharField(blank=True, default='', max_length=64)),
                ('score_topn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('store_topn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('model_scope', models.CharField(blank=True, default='', max_length=128)),
                ('model_degraded', models.BooleanField(default=False)),
                ('model_degrade_reason', models.CharField(blank=True, default='', max_length=512)),
                ('source_periods', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics_score_snapshots', to='market_data.security')),
            ],
            options={
                'db_table': 'metrics_score_snapshot',
            },
        ),
        migrations.CreateModel(
            name='MetricsScoreDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_key', models.CharField(max_length=64)),
                ('dimension_name', models.CharField(blank=True, default='', max_length=128)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=7)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(max_length=32)),
                ('available_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='metrics.metricsscoresnapshot')),
            ],
            options={
                'db_table': 'metrics_score_dimension',
            },
        ),
        migrations.AddIndex(
            model_name='metricsscoresnapshot',
            index=models.Index(fields=['security', 'score_type', '-asof_date', '-created_at'], name='mss_sec_type_asof'),
        ),
        migrations.AddIndex(
            model_name='metricsscoresnapshot',
            index=models.Index(fields=['score_type', '-asof_date', 'score_status'], name='mss_type_date_status'),
        ),
        migrations.AddIndex(
            model_name='metricsscoresnapshot',
            index=models.Index(fields=['score_type', 'score'], name='mss_type_score'),
        ),
        migrations.AddConstraint(
            model_name='metricsscoresnapshot',
            constraint=models.UniqueConstraint(fields=('security', 'score_type', 'input_fingerprint'), name='mss_sec_type_fp'),
        ),
        migrations.AddIndex(
            model_name='metricsscoredimension',
            index=models.Index(fields=['dimension_key', 'score', 'status'], name='msd_key_score_status'),
        ),
        migrations.AddConstraint(
            model_name='metricsscoredimension',
            constraint=models.UniqueConstraint(fields=('snapshot', 'dimension_key'), name='msd_snapshot_dimension'),
        ),
    ]
