# Generated by Django 5.2.4 on 2025-08-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_rename_stocktopbottomquantile_stockgainlossquantile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktopbottomhistory',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='一个周期长度'),
        ),
    ]
