# Generated by Django 5.2.4 on 2025-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_stockfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日低于25%统计的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日低于25%统计的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计10%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于25%统计的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日低于25%统计的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日低于25%统计的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='amount_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的成交额_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日低于25%统计的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日低于25%统计的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计10%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='25日低于25%统计的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日低于25%统计的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日低于25%统计的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='close_qfq_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA10'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma120',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA120'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma16',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA16'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma200',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA200'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA25'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma43',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA43'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA6'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma60',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA60'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma90',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MA90'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日低于25%统计的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日低于25%统计的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于10%统计的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于25%统计的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日低于25%统计的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日低于25%统计的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pb_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的市净率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日低于25%统计的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日低于25%统计的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于10%统计的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于25%统计的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日低于25%统计的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日低于25%统计的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pe_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的市盈率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日低于25%统计的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日低于25%统计的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于10%统计的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于25%统计的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日低于25%统计的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日低于25%统计的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ps_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的市销率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日低于25%统计的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日低于25%统计的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于10%统计的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于25%统计的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日低于25%统计的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日低于25%统计的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='turnover_rate_f_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的换手率_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计25%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计25%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计10%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计25%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计25%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计25%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='vol_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的vol_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_120d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计10%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_120d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日低于25%统计的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_120d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计50%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_120d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计75%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_120d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='120日内统计90%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_200d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计10%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_200d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日低于25%统计的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_200d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计50%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_200d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计75%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_200d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='200日内统计90%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_30d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于10%统计的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_30d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日低于25%统计的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_30d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计50%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_30d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计75%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_30d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='30日内统计90%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_60d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计10%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_60d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日低于25%统计的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_60d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计50%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_60d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计75%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_60d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='60日内统计90%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_90d_10pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计10%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_90d_25pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日低于25%统计的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_90d_50pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计50%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_90d_75pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计75%的量比_qfq'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volume_ratio_90d_90pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='90日内统计90%的量比_qfq'),
        ),
        migrations.AlterField(
            model_name='stockfeatures',
            name='turnover_rate_f',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='换手率(自由流通)'),
        ),
    ]
