# Generated by Django 5.2.4 on 2025-11-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_stockfeatures_amount_120d_10pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfeatures',
            name='atr_10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ATR_10'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='atr_14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ATR_14'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='atr_20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ATR_20'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='atr_25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ATR_25'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='atr_6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ATR_6'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volatility_ratio_10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='波动率比_10'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volatility_ratio_14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='波动率比_14'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volatility_ratio_20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='波动率比_20'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volatility_ratio_25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='波动率比_25'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='volatility_ratio_6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='波动率比_6'),
        ),
    ]
