# Generated by Django 5.2.4 on 2025-11-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_stockfeatures_atr_10_stockfeatures_atr_14_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfeatures',
            name='ma10_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA10_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma120_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA120_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma16_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA16_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma200_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA200_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma25_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA25_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma43_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA43_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma60_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA60_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='ma6_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA6_trend'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='pct_vol_chg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='交易量变化%'),
        ),
    ]
