# Generated by Django 5.2.4 on 2025-11-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_stockfeatures_ma10_trend_stockfeatures_ma120_trend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfeatures',
            name='ma90_trend',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='MA90_trend'),
        ),
    ]
