# Generated by Django 5.2.4 on 2025-11-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_stockfeatures_ma90_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfeatures',
            name='top_bottom_volatility_optimized',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='优化的涨跌幅大的峰谷'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='top_bottom_volatility_stat',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='统计涨跌幅大的峰谷'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='top_or_bottom',
            field=models.CharField(blank=True, default='N', max_length=1, null=True, verbose_name='scipy峰谷'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='top_or_bottom_optimized',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='优化校验峰谷'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='top_or_bottom_stat',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='统计峰谷'),
        ),
        migrations.AddField(
            model_name='stockfeatures',
            name='top_or_bottom_stat_optimized',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='优化统计峰谷'),
        ),
    ]
