# Generated by Django 5.2.4 on 2025-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_stockcostfeature_stockfundamentalfeature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='close_atr_10_diff',
            new_name='close_atr_10_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='close_atr_14_diff',
            new_name='close_atr_14_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='close_atr_20_diff',
            new_name='close_atr_20_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='close_atr_25_diff',
            new_name='close_atr_25_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='close_atr_6_diff',
            new_name='close_atr_6_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='high_atr_10_diff',
            new_name='high_atr_10_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='high_atr_14_diff',
            new_name='high_atr_14_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='high_atr_20_diff',
            new_name='high_atr_20_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='high_atr_25_diff',
            new_name='high_atr_25_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='high_atr_6_diff',
            new_name='high_atr_6_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='low_atr_10_diff',
            new_name='low_atr_10_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='low_atr_14_diff',
            new_name='low_atr_14_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='low_atr_20_diff',
            new_name='low_atr_20_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='low_atr_25_diff',
            new_name='low_atr_25_upper_diff',
        ),
        migrations.RenameField(
            model_name='stocktechfeature',
            old_name='low_atr_6_diff',
            new_name='low_atr_6_upper_diff',
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='is_bearish_and_divergent',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='is_bullish_and_divergent',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='is_double_top',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='is_lower_shadow_shape',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='is_t_shape',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='is_upper_shadow_shape',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='ma6_ma10_entangled',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='ma6_ma10_ma25_entangled',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='ma6_ma10_ma25_ma60_entangled',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='ma6_ma10_ma25_ma60_ma120_ma200_entangled',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma10',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma10状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma120',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma120状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma16',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma16状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma200',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma200状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma25',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma25状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma43',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma43状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma6',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma6状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma60',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma60状态'),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='vol_status_ma90',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='交易量ma90状态'),
        ),
    ]
