# Generated by Django 5.2.4 on 2025-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_rename_close_atr_10_diff_stocktechfeature_close_atr_10_upper_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_10_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_10_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_10_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_14_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_14_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_14_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_20_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_20_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_20_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_25_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_25_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_25_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_6_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_6_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='close_atr_6_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_10_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_10_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_10_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_14_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_14_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_14_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_20_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_20_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_20_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_25_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_25_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_25_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_6_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_6_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='high_atr_6_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_10_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_10_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_10_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_14_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_14_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_14_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_20_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_20_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_20_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_25_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_25_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_25_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_6_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_6_x2_lower_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktechfeature',
            name='low_atr_6_x2_upper_diff',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
