# Generated by Django 5.2.4 on 2025-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_stocktechfeature_close_atr_10_lower_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma10',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma10状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma120',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma120状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma16',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma16状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma200',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma200状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma25',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma25状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma43',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma43状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma6',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma6状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma60',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma60状态'),
        ),
        migrations.AlterField(
            model_name='stocktechfeature',
            name='vol_status_ma90',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='交易量ma90状态'),
        ),
    ]
