# Generated by Django 5.2.4 on 2026-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_stockcombinedfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcombinedfeature',
            name='body',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='主体'),
        ),
        migrations.AddField(
            model_name='stockcombinedfeature',
            name='lower_shadow',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='下影线'),
        ),
        migrations.AddField(
            model_name='stockcombinedfeature',
            name='pct_o2c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='开盘-收盘%'),
        ),
        migrations.AddField(
            model_name='stockcombinedfeature',
            name='upper_shadow',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='上影线'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktopbottomhistory',
            unique_together={('trade_date', 'ts_code', 'freq', 'top_or_bottom', 'period')},
        ),
    ]
