# Generated by Django 5.2.4 on 2026-01-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_stockcombinedfeature_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcombinedfeature',
            name='shadow_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='影线比率'),
        ),
    ]
