# Generated by Django 5.2.4 on 2026-01-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_stockcombinedfeature_shadow_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcombinedfeature',
            name='chip_concentration',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='筹码集中度'),
        ),
    ]
