# Generated by Django 5.2.4 on 2025-08-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='行业名称')),
                ('name_pinyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='行业名称拼音')),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='省份')),
                ('country', models.CharField(blank=True, default='中国', max_length=50, verbose_name='国家')),
                ('name_pinyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份拼音')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='交易代码')),
                ('name', models.CharField(db_index=True, help_text='股票简称', max_length=50, verbose_name='股票名称')),
                ('fullname', models.CharField(blank=True, help_text='公司全称', max_length=100, null=True, verbose_name='公司名称')),
                ('enname', models.CharField(blank=True, help_text='公司英文全称', max_length=100, null=True, verbose_name='英文全称')),
                ('cnspell', models.CharField(blank=True, help_text='股票简称拼音', max_length=50, null=True, verbose_name='股票名称拼音')),
                ('market', models.CharField(blank=True, help_text='主板/创业板/科创板等', max_length=50, null=True, verbose_name='市场类型')),
                ('exchange', models.CharField(blank=True, help_text='如 SZSE/SHSE', max_length=10, null=True, verbose_name='交易所代码')),
                ('curr_type', models.CharField(help_text='交易货币类型，如 CNY', max_length=10, verbose_name='货币类型')),
                ('list_status', models.CharField(blank=True, choices=[('L', '上市'), ('D', '退市'), ('P', '暂停上市')], help_text='L:上市 D:退市 P:暂停上市', max_length=1, null=True, verbose_name='上市状态')),
                ('list_date', models.DateField(blank=True, help_text='公司上市日期', null=True, verbose_name='上市日期')),
                ('delist_date', models.DateField(blank=True, help_text='公司退市日期', null=True, verbose_name='退市日期')),
                ('is_hs', models.CharField(blank=True, choices=[('S', '沪股通'), ('H', '深股通'), ('N', '否')], help_text='S:沪股通 H:深股通 N:否', max_length=10, null=True, verbose_name='是否沪深港通标的')),
                ('act_name', models.CharField(blank=True, help_text='实际控制人名称', max_length=50, null=True, verbose_name='实控人名称')),
                ('act_ent_type', models.CharField(blank=True, help_text='实际控制人企业性质', max_length=50, null=True, verbose_name='实控人企业性质')),
                ('asset', models.CharField(blank=True, choices=[('E', '股票'), ('I', '指数')], default='E', help_text='E:股票 I:指数', max_length=1, null=True, verbose_name='股票/指数')),
                ('area', models.ForeignKey(blank=True, help_text='公司注册省份', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporations', to='stockdata.area', verbose_name='省份')),
                ('industry', models.ForeignKey(blank=True, help_text='所属行业', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporations', to='stockdata.industry', verbose_name='行业')),
            ],
            options={
                'verbose_name': '股票公司信息',
                'verbose_name_plural': '股票公司信息',
                'ordering': ['ts_code'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='城市')),
                ('name_pinyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市拼音')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='stockdata.area', verbose_name='省份')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['name'],
                'unique_together': {('name', 'area')},
            },
        ),
        migrations.CreateModel(
            name='StockTradingHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_index=True, help_text='如 000001.SZ', max_length=10, verbose_name='交易代码')),
                ('trade_date', models.DateField(db_index=True, help_text='如 2020-05-05', verbose_name='交易日')),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='开盘价')),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最高价')),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最低价')),
                ('pre_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='前日收盘价')),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='收盘价')),
                ('change', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格变化')),
                ('pct_change', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='价格变化%')),
                ('vol', models.BigIntegerField(blank=True, help_text='单位：股', null=True, verbose_name='交易量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='单位：元', max_digits=20, null=True, verbose_name='金额')),
                ('adj_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='复权因子')),
                ('open_hfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='开盘价_hfq')),
                ('open_qfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='开盘价_qfq')),
                ('close_hfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='收盘价_hfq')),
                ('close_qfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='收盘价_qfq')),
                ('high_hfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最高价_hfq')),
                ('high_qfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最高价_qfq')),
                ('low_hfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最低价_hfq')),
                ('low_qfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最低价_qfq')),
                ('pre_close_hfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='前日收盘价_hfq')),
                ('pre_close_qfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='前日收盘价_qfq')),
                ('change_hfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格变化_hfq')),
                ('change_qfq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格变化_qfq')),
                ('pct_change_hfq', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='价格变化%_hfq')),
                ('pct_change_qfq', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='价格变化%_qfq')),
                ('macd_dif', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MACD_DIF')),
                ('macd_dea', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MACD_DEA')),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='MACD')),
                ('kdj_k', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='KDJ_K')),
                ('kdj_d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='KDJ_D')),
                ('kdj_j', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='KDJ_J')),
                ('rsi_6', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='RSI_6')),
                ('rsi_12', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='RSI_12')),
                ('rsi_24', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='RSI_24')),
                ('boll_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='BOLL_UPPER')),
                ('boll_middle', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='BOLL_MIDDLE')),
                ('boll_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='BOLL_LOWER')),
                ('cci', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='CCI')),
                ('freq', models.CharField(default='D', help_text='如 D 日线，W 周线，M 月线', max_length=5, verbose_name='周期')),
                ('corporation', models.ForeignKey(blank=True, help_text='关联的股票公司信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_history', to='stockdata.corporation', verbose_name='公司')),
            ],
            options={
                'verbose_name': '股票交易历史',
                'verbose_name_plural': '股票交易历史',
                'ordering': ['-trade_date'],
                'get_latest_by': 'id',
                'unique_together': {('trade_date', 'ts_code')},
            },
        ),
    ]
