# Generated by Django 5.2.4 on 2025-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0006_alter_stockfundamentalhistory_pb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='turnover_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=12, null=True, verbose_name='换手率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='turnover_rate_f',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=12, null=True, verbose_name='换手率(自由流通)'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='volume_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='量比'),
        ),
    ]
