# Generated by Django 5.2.4 on 2025-09-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0008_stockfundamentalhistory_freq_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocktradinghistory',
            unique_together={('trade_date', 'ts_code', 'freq')},
        ),
    ]
