# Generated by Django 5.2.4 on 2025-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0011_alter_stocktradinghistory_pct_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundamentalhistory',
            name='is_pulled_by_client',
            field=models.BooleanField(default=False, help_text='该数据是否由客户端拉取', verbose_name='是否由客户端拉取'),
        ),
        migrations.AddField(
            model_name='stocktradinghistory',
            name='is_pulled_by_client',
            field=models.BooleanField(default=False, help_text='该数据是否由客户端拉取', verbose_name='是否由客户端拉取'),
        ),
    ]
