# Generated by Django 5.2.4 on 2025-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0013_stockcosthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcosthistory',
            name='winner_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=12, null=True, verbose_name='胜率'),
        ),
    ]
