# Generated by Django 5.2.4 on 2025-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0014_alter_stockcosthistory_winner_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcosthistory',
            name='is_pulled_by_client',
            field=models.BooleanField(default=False, help_text='该数据是否由客户端拉取', verbose_name='是否由客户端拉取'),
        ),
    ]
