# Generated by Django 5.2.4 on 2025-11-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0013_alter_stockfundamentalhistory_is_pulled_by_client_and_more'),
        ('stockdata', '0015_stockcosthistory_is_pulled_by_client'),
    ]

    operations = [
    ]
