# Generated by Django 4.2 on 2026-09-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0016_merge_20251106_2137"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockcosthistory",
            unique_together={("ts_code", "trade_date", "freq")},
        ),
    ]