# Generated by Django 5.2.4 on 2026-03-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCacheImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cache_dir', models.CharField(max_length=512)),
                ('endpoints', models.CharField(max_length=512)),
                ('files_scanned', models.IntegerField(default=0)),
                ('rows_parsed', models.IntegerField(default=0)),
                ('rows_upserted', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'earnings_financial_cache_import_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCacheRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=64)),
                ('ts_code', models.CharField(db_index=True, max_length=16)),
                ('ann_date', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('end_date', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('period', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('row_signature', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('source_file', models.CharField(blank=True, default='', max_length=512)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'earnings_financial_cache_record',
                'indexes': [models.Index(fields=['endpoint', 'ts_code'], name='idx_fin_cache_ep_code'), models.Index(fields=['ts_code', 'end_date'], name='idx_fin_cache_code_end')],
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'ts_code', 'ann_date', 'end_date', 'period', 'row_signature'), name='uq_earnings_fin_cache_record')],
            },
        ),
    ]
