# Generated by Django 5.2.4 on 2026-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_forecast', '0005_financial_endpoint_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialbalancesheetviprecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialcashflowviprecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialdisclosuredaterecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialdividendrecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialexpressviprecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialfinaauditrecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialfinaindicatorviprecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialfinamainbzviprecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialforecastviprecord',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='financialincomerecord',
            name='payload',
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='accounts_receiv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='comp_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='f_ann_date',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='inventories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='lt_borr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='money_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='st_borr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='total_assets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='total_hldr_eqy_exc_min_int',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbalancesheetviprecord',
            name='total_liab',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialcashflowviprecord',
            name='comp_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialcashflowviprecord',
            name='f_ann_date',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialcashflowviprecord',
            name='n_cash_flows_fnc_act',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialcashflowviprecord',
            name='n_cashflow_act',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialcashflowviprecord',
            name='n_cashflow_inv_act',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialcashflowviprecord',
            name='n_incr_cash_cash_equ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialcashflowviprecord',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialdisclosuredaterecord',
            name='actual_date',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialdisclosuredaterecord',
            name='modify_date',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialdisclosuredaterecord',
            name='pre_date',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialdividendrecord',
            name='cash_div',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdividendrecord',
            name='ex_date',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialdividendrecord',
            name='record_date',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialdividendrecord',
            name='stk_div',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpressviprecord',
            name='diluted_eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpressviprecord',
            name='n_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpressviprecord',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialexpressviprecord',
            name='total_assets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaauditrecord',
            name='audit_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaauditrecord',
            name='audit_result',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='assets_turn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='cash_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='comp_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='current_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='debt_to_assets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='f_ann_date',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='grossprofit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='netprofit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='netprofit_yoy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='ocf_to_or',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='q_dt_roe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='quick_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='roa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='roe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='roe_dt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinaindicatorviprecord',
            name='tr_yoy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinamainbzviprecord',
            name='bz_item',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='financialfinamainbzviprecord',
            name='bz_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfinamainbzviprecord',
            name='bz_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialforecastviprecord',
            name='net_profit_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialforecastviprecord',
            name='net_profit_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialforecastviprecord',
            name='p_change_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialforecastviprecord',
            name='p_change_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialforecastviprecord',
            name='type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='basic_eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='comp_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='diluted_eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='f_ann_date',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='n_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='n_income_attr_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='operate_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='total_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialincomerecord',
            name='total_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialbalancesheetviprecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialcashflowviprecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialdisclosuredaterecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialdividendrecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialexpressviprecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialfinaauditrecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialfinaindicatorviprecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialfinamainbzviprecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialforecastviprecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='financialincomerecord',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
