# Generated by Django 5.2.4 on 2026-05-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalBacktestRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('batch_key', models.CharField(db_index=True, default='traditional_value_exit', max_length=64)),
                ('strategy_name', models.CharField(db_index=True, default='traditional_value_exit', max_length=64)),
                ('status', models.CharField(db_index=True, default='success', max_length=16)),
                ('scope', models.CharField(default='ALL', max_length=32)),
                ('market', models.CharField(default='CN', max_length=10)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('result_file', models.CharField(blank=True, default='', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['batch_key', 'updated_at'], name='backtest_tr_batch_k_d54a8d_idx'), models.Index(fields=['strategy_name', 'updated_at'], name='backtest_tr_strateg_f5f26e_idx'), models.Index(fields=['start_date', 'end_date'], name='backtest_tr_start_d_e6a6f8_idx')],
            },
        ),
    ]
