# Generated by Django 5.1.1 on 2026-09-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0004_marketregimestate_marketregimesnapshot_regimeevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('level', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(max_length=24)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('standardized_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('momentum', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('activity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fear', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('universe_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('coverage', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('engine_version', models.CharField(max_length=32)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(default='CN', max_length=8)),
                ('scope_type', models.CharField(default='MARKET', max_length=16)),
                ('scope_code', models.CharField(default='ALL_A', max_length=32)),
            ],
            options={
                'db_table': 'market_sentiment_snapshot',
                'indexes': [models.Index(fields=['market', 'scope_type', 'scope_code', 'engine_version', '-trade_date'], name='ms_market_scope_dt')],
                'constraints': [models.UniqueConstraint(fields=('market', 'scope_type', 'scope_code', 'trade_date', 'engine_version'), name='ms_market_snapshot_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StockSentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('level', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(max_length=24)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('standardized_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('momentum', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('activity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fear', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('universe_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('coverage', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('engine_version', models.CharField(max_length=32)),
                ('source_trade_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer_type', models.CharField(blank=True, max_length=32)),
                ('peer_code', models.CharField(blank=True, max_length=128)),
                ('peer_name', models.CharField(blank=True, max_length=128)),
                ('peer_count', models.PositiveIntegerField(default=0)),
                ('normalization_mode', models.CharField(blank=True, max_length=32)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_snapshots', to='market_data.security')),
            ],
            options={
                'db_table': 'stock_sentiment_snapshot',
            },
        ),
        migrations.CreateModel(
            name='StockSentimentFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_code', models.CharField(max_length=32)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('effective_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('contribution', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='market_sentiment.stocksentimentsnapshot')),
            ],
            options={
                'db_table': 'stock_sentiment_factor',
            },
        ),
        migrations.CreateModel(
            name='MarketSentimentFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_code', models.CharField(max_length=32)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('effective_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('contribution', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='market_sentiment.marketsentimentsnapshot')),
            ],
            options={
                'db_table': 'market_sentiment_factor',
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'factor_code'), name='ms_market_factor_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='stocksentimentsnapshot',
            index=models.Index(fields=['security', 'engine_version', '-trade_date'], name='ms_stock_sec_dt'),
        ),
        migrations.AddIndex(
            model_name='stocksentimentsnapshot',
            index=models.Index(fields=['trade_date', 'engine_version', '-score'], name='ms_stock_score_dt'),
        ),
        migrations.AddConstraint(
            model_name='stocksentimentsnapshot',
            constraint=models.UniqueConstraint(fields=('security', 'trade_date', 'engine_version'), name='ms_stock_snapshot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stocksentimentfactor',
            constraint=models.UniqueConstraint(fields=('snapshot', 'factor_code'), name='ms_stock_factor_uniq'),
        ),
    ]
