# Generated by Django 5.2.14 on 2026-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsentimentsnapshot',
            name='status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='stocksentimentsnapshot',
            name='status',
            field=models.CharField(max_length=32),
        ),
    ]
