# Generated by Django 5.2.4 on 2025-08-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0002_rename_boll_middle_stocktradinghistory_boll_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_index=True, help_text='如 000001.SZ', max_length=10, verbose_name='交易代码')),
                ('trade_date', models.DateField(blank=True, db_index=True, help_text='如 2020-05-05', null=True, verbose_name='交易日期')),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='收盘价')),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=8, null=True, verbose_name='换手率')),
                ('turnover_rate_f', models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=8, null=True, verbose_name='换手率(自由流通)')),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='量比')),
                ('pe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='市盈率')),
                ('pe_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='市盈率TTM')),
                ('pb', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='市净率')),
                ('ps', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='市销率')),
                ('ps_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='市销率TTM')),
                ('dv_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='股息')),
                ('dv_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='股息率TTM')),
                ('total_share', models.DecimalField(blank=True, decimal_places=2, help_text='单位：股', max_digits=20, null=True, verbose_name='总股本')),
                ('float_share', models.DecimalField(blank=True, decimal_places=2, help_text='单位：股', max_digits=20, null=True, verbose_name='流通股本')),
                ('free_share', models.DecimalField(blank=True, decimal_places=2, help_text='单位：股', max_digits=20, null=True, verbose_name='自由流通股本')),
                ('total_mv', models.DecimalField(blank=True, decimal_places=2, help_text='单位：元', max_digits=20, null=True, verbose_name='总市值')),
                ('circ_mv', models.DecimalField(blank=True, decimal_places=2, help_text='单位：元', max_digits=20, null=True, verbose_name='流通市值')),
                ('corporation', models.ForeignKey(blank=True, help_text='关联的股票公司信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamental_history', to='stockdata.corporation', verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司基本面',
                'verbose_name_plural': '公司基本面',
                'ordering': ['-ts_code'],
                'get_latest_by': 'id',
                'unique_together': {('ts_code', 'trade_date')},
            },
        ),
    ]
