# Generated by Django 5.2.4 on 2025-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0005_corporationbasic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='pb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市盈率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='pe_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市盈率TTM'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='ps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市销率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='ps_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市销率TTM'),
        ),
    ]
