# Generated by Django 5.2.4 on 2025-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0007_alter_stockfundamentalhistory_turnover_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundamentalhistory',
            name='freq',
            field=models.CharField(default='D', help_text='如 D 日线，W 周线，M 月线', max_length=5, verbose_name='周期'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='dv_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='股息'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='dv_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='股息率TTM'),
        ),
    ]
