# Generated by Django 5.2.4 on 2026-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings_forecast", "0006_remove_financialbalancesheetviprecord_payload_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalCorporation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts_code", models.CharField(db_index=True, max_length=16, unique=True)),
                ("industry_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "earnings_dim_corporation",
            },
        ),
        migrations.CreateModel(
            name="LocalFundamentalHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts_code", models.CharField(db_index=True, max_length=16)),
                ("trade_date", models.DateField(db_index=True)),
                ("freq", models.CharField(db_index=True, default="D", max_length=8)),
                ("pe", models.FloatField(blank=True, null=True)),
                ("pb", models.FloatField(blank=True, null=True)),
                ("ps", models.FloatField(blank=True, null=True)),
                ("total_mv", models.FloatField(blank=True, null=True)),
                ("circ_mv", models.FloatField(blank=True, null=True)),
                ("turnover_rate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "earnings_mkt_fundamental_history",
                "indexes": [
                    models.Index(fields=["trade_date", "freq"], name="idx_earn_mkt_funda_date_freq"),
                    models.Index(fields=["ts_code", "trade_date"], name="idx_earn_mkt_funda_code_date"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("ts_code", "trade_date", "freq"), name="uq_earn_mkt_funda_code_date_freq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocalIndustry",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "earnings_dim_industry",
            },
        ),
        migrations.CreateModel(
            name="LocalTradingHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts_code", models.CharField(db_index=True, max_length=16)),
                ("trade_date", models.DateField(db_index=True)),
                ("freq", models.CharField(db_index=True, default="D", max_length=8)),
                ("close", models.FloatField(blank=True, null=True)),
                ("pct_change", models.FloatField(blank=True, null=True)),
                ("vol", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "earnings_mkt_trading_history",
                "indexes": [
                    models.Index(fields=["trade_date", "freq"], name="idx_earn_mkt_trade_date_freq"),
                    models.Index(fields=["ts_code", "trade_date"], name="idx_earn_mkt_trade_code_date"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("ts_code", "trade_date", "freq"), name="uq_earn_mkt_trade_code_date_freq"),
                ],
            },
        ),
    ]
