# Generated by Django 5.2.4 on 2025-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='funda_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化基本面数据', verbose_name='基本面数据已初始化'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='trading_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化交易数据', verbose_name='交易数据已初始化'),
        ),
    ]
