# Generated by Django 5.2.4 on 2025-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_corporation_funda_inited_corporation_trading_inited'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundamentalhistory',
            name='freq',
            field=models.CharField(default='D', help_text='如 D 日线，W 周线，M 月线', max_length=5, verbose_name='周期'),
        ),
    ]
