# Generated by Django 5.2.4 on 2025-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0003_stockfundamentalhistory_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='monthly_funda_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化月基本面数据', verbose_name='月基本面数据已初始化'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='monthly_trading_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化月交易数据', verbose_name='月交易数据已初始化'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='weekly_funda_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化周基本面数据', verbose_name='周基本面数据已初始化'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='weekly_trading_inited',
            field=models.BooleanField(default=False, help_text='是否已初始化周交易数据', verbose_name='周交易数据已初始化'),
        ),
    ]
