# Generated by Django 5.2.4 on 2025-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0006_alter_stockfundamentalhistory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='dv_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='股息'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='dv_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='股息率TTM'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='pb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市盈率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='pe_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市盈率TTM'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='ps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市销率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='ps_ttm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='市销率TTM'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='turnover_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=12, null=True, verbose_name='换手率'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='turnover_rate_f',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='单位：%', max_digits=12, null=True, verbose_name='换手率(自由流通)'),
        ),
        migrations.AlterField(
            model_name='stockfundamentalhistory',
            name='volume_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='量比'),
        ),
    ]
