"""
Django settings for smartinvestor_be project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 默认初始化交易记录和基本面记录条数
INIT_DATA_LIMIT = 400

# 默认交易记录条数
DEFAULT_HISTORY_COUNT = 60

# ETL BaseURL
ETL_BASE_URL = "http://127.0.0.1:5000/api"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-aycngl&@e=&ui0pxnsf955l=y(i-b_&0)kf!si)m7m)hjyx4bk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "corsheaders",
    # Your third-party apps here
    "api.apps.ApiConfig",
    "users.apps.UsersConfig",
    "datastore.apps.DatastoreConfig",
    "prediction.apps.PredictionConfig",
    "backtest.apps.BacktestConfig",
    "valuation.apps.ValuationConfig",
    "valuation_risk.apps.ValuationRiskConfig",
    "supply_chain.apps.SupplyChainConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 跨域资源共享
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smartinvestor_be.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "smartinvestor_be.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# for deployment
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "smartinvestor",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# Dedicated earnings database for local valuation financial tables.
DATABASES["earnings"] = {
    "ENGINE": "django.db.backends.postgresql_psycopg2",
    "NAME": os.getenv("EARNINGS_DB_NAME", "smartinvestor_earnings_uat"),
    "USER": os.getenv("EARNINGS_DB_USER", DATABASES["default"].get("USER", "postgres")),
    "PASSWORD": os.getenv("EARNINGS_DB_PASSWORD", DATABASES["default"].get("PASSWORD", "postgres")),
    "HOST": os.getenv("EARNINGS_DB_HOST", DATABASES["default"].get("HOST", "localhost")),
    "PORT": os.getenv("EARNINGS_DB_PORT", DATABASES["default"].get("PORT", "5432")),
}

# SQLite configuration (for development or testing)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# 指定自定义用户模型
AUTH_USER_MODEL = 'users.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = BASE_DIR / "static"

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://localhost:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5173",
]

# Earnings forecast service integration
EARNINGS_SERVICE_BASE_URL = os.getenv("EARNINGS_SERVICE_BASE_URL", "http://127.0.0.1:5002")
EARNINGS_SERVICE_TIMEOUT_SECONDS = float(os.getenv("EARNINGS_SERVICE_TIMEOUT_SECONDS", "4"))
EARNINGS_SERVICE_PREDICT_TIMEOUT_SECONDS = float(
    os.getenv("EARNINGS_SERVICE_PREDICT_TIMEOUT_SECONDS", "45")
)
EARNINGS_SERVICE_RETRY_COUNT = int(os.getenv("EARNINGS_SERVICE_RETRY_COUNT", "1"))
EARNINGS_SIGNAL_CACHE_SECONDS = int(os.getenv("EARNINGS_SIGNAL_CACHE_SECONDS", "1800"))
PREDICTIVE_UNDERVALUED_MIN_SIGNAL_SCORE_DEFAULT = float(
    os.getenv("PREDICTIVE_UNDERVALUED_MIN_SIGNAL_SCORE_DEFAULT", "100")
)

# Predictive return optimization: robustness constraints + cross-period calibration.
PREDICTIVE_RETURN_OPTIMIZATION_ENABLED = os.getenv("PREDICTIVE_RETURN_OPTIMIZATION_ENABLED", "1").lower() in {
    "1", "true", "yes", "on"
}
PREDICTIVE_RETURN_ROBUSTNESS_ENABLED = os.getenv("PREDICTIVE_RETURN_ROBUSTNESS_ENABLED", "1").lower() in {
    "1", "true", "yes", "on"
}
PREDICTIVE_RETURN_CALIBRATION_ENABLED = os.getenv("PREDICTIVE_RETURN_CALIBRATION_ENABLED", "1").lower() in {
    "1", "true", "yes", "on"
}
PREDICTIVE_RETURN_MIN_PCT = float(os.getenv("PREDICTIVE_RETURN_MIN_PCT", "-40"))
PREDICTIVE_RETURN_MAX_PCT = float(os.getenv("PREDICTIVE_RETURN_MAX_PCT", "120"))
PREDICTIVE_RETURN_DIVERGENCE_CAP_PCT = float(os.getenv("PREDICTIVE_RETURN_DIVERGENCE_CAP_PCT", "35"))
PREDICTIVE_RETURN_SHRINK_WEIGHT_MIN = float(os.getenv("PREDICTIVE_RETURN_SHRINK_WEIGHT_MIN", "0.35"))
PREDICTIVE_RETURN_SHRINK_WEIGHT_MAX = float(os.getenv("PREDICTIVE_RETURN_SHRINK_WEIGHT_MAX", "0.85"))
PREDICTIVE_RETURN_STALE_HALF_LIFE_DAYS = float(os.getenv("PREDICTIVE_RETURN_STALE_HALF_LIFE_DAYS", "180"))
PREDICTIVE_RETURN_CALIBRATION_BIAS = float(os.getenv("PREDICTIVE_RETURN_CALIBRATION_BIAS", "0"))
PREDICTIVE_RETURN_CALIBRATION_SLOPE = float(os.getenv("PREDICTIVE_RETURN_CALIBRATION_SLOPE", "0.85"))

# Predictive tiered valuation template (tab-2 supplement for predictive valuation panel)
PREDICTIVE_TIER_TEMPLATE_CONFIG = {
    "reliability": {
        "score_min": 5.0,
        "score_max": 95.0,
        "default_signal_score": 50.0,
        "risk_penalty": {
            "HIGH": 18.0,
            "MEDIUM": 8.0,
            "LOW": 0.0,
            "DEFAULT": 5.0,
        },
        "dispersion_penalty_multiplier": 60.0,
        "dispersion_penalty_cap": 25.0,
        "freshness_days_per_penalty": 8.0,
        "freshness_penalty_cap": 20.0,
    },
    "style_thresholds": {
        "high_confidence_min": 75.0,
        "low_confidence_max": 50.0,
    },
    "styles": {
        "high_confidence": {
            "label": "高可信度",
            "blend_high_weight": {
                "conservative": 0.14,
                "balanced": 0.62,
                "aggressive": 0.80,
            },
        },
        "balanced": {
            "label": "均衡可信度",
            "blend_high_weight": {
                "conservative": 0.14,
                "balanced": 0.50,
                "aggressive": 0.80,
            },
        },
        "low_confidence": {
            "label": "谨慎可信度",
            "blend_high_weight": {
                "conservative": 0.14,
                "balanced": 0.38,
                "aggressive": 0.80,
            },
        },
    },
    "tier_ranges": {
        "conservative": (0.95, 1.04),
        "balanced": (0.95, 1.08),
        "aggressive": (0.95, 1.15),
    },
    "position_guidance": {
        "below_conservative": {
            "default": {"range": "55%-70%", "message": "低于风控区间下沿，可分批提高仓位。"},
            "high_confidence": {"range": "65%-80%", "message": "低于风控区间下沿且可信度高，可积极分批提高仓位。"},
        },
        "below_balanced": {
            "default": {"range": "45%-65%", "message": "低于平衡区间，可逐步加仓。"},
            "low_confidence": {"range": "40%-55%", "message": "低于平衡区间但可信度偏低，建议温和加仓。"},
        },
        "within_balanced": {
            "default": {"range": "35%-55%", "message": "位于平衡区间，维持中性仓位。"},
        },
        "within_aggressive": {
            "default": {"range": "25%-40%", "message": "处于偏高区间，可逐步降低仓位。"},
        },
        "above_aggressive": {
            "default": {"range": "15%-30%", "message": "高于进攻区间上沿，建议偏防守仓位。"},
            "high_confidence": {"range": "20%-35%", "message": "高于进攻区间上沿，建议偏防守仓位并等待更优风险收益比。"},
        },
    },
}

# Traditional valuation optimization: robustness constraints + cross-period calibration.
TRADITIONAL_RETURN_OPTIMIZATION_ENABLED = os.getenv("TRADITIONAL_RETURN_OPTIMIZATION_ENABLED", "1").lower() in {
    "1", "true", "yes", "on"
}
TRADITIONAL_RETURN_CALIBRATION_ENABLED = os.getenv("TRADITIONAL_RETURN_CALIBRATION_ENABLED", "1").lower() in {
    "1", "true", "yes", "on"
}
TRADITIONAL_RETURN_MIN_PCT = float(os.getenv("TRADITIONAL_RETURN_MIN_PCT", "-50"))
TRADITIONAL_RETURN_MAX_PCT = float(os.getenv("TRADITIONAL_RETURN_MAX_PCT", "150"))
TRADITIONAL_RETURN_DISPERSION_REF = float(os.getenv("TRADITIONAL_RETURN_DISPERSION_REF", "0.35"))
TRADITIONAL_RETURN_SHRINK_WEIGHT_MIN = float(os.getenv("TRADITIONAL_RETURN_SHRINK_WEIGHT_MIN", "0.35"))
TRADITIONAL_RETURN_SHRINK_WEIGHT_MAX = float(os.getenv("TRADITIONAL_RETURN_SHRINK_WEIGHT_MAX", "0.85"))
TRADITIONAL_RETURN_CALIBRATION_BIAS = float(os.getenv("TRADITIONAL_RETURN_CALIBRATION_BIAS", "0"))
TRADITIONAL_RETURN_CALIBRATION_SLOPE = float(os.getenv("TRADITIONAL_RETURN_CALIBRATION_SLOPE", "0.9"))

# Traditional valuation: prefer local financial DB tables before Tushare API.
VALUATION_USE_LOCAL_FINANCIAL_DB = os.getenv("VALUATION_USE_LOCAL_FINANCIAL_DB", "1").lower() in {
    "1", "true", "yes", "on"
}
VALUATION_LOCAL_FINANCIAL_ONLY = os.getenv("VALUATION_LOCAL_FINANCIAL_ONLY", "0").lower() in {
    "1", "true", "yes", "on"
}
VALUATION_LOCAL_FINANCIAL_DB_ALIAS = os.getenv("VALUATION_LOCAL_FINANCIAL_DB_ALIAS", "earnings")

# Valuation snapshot table prefix switch:
# - "prediction": current table prefix before rename
# - "valuation": target prefix after DB table rename
_valuation_table_prefix = str(os.getenv("VALUATION_TABLE_PREFIX", "valuation") or "valuation").strip().lower()
VALUATION_TABLE_PREFIX = _valuation_table_prefix if _valuation_table_prefix in {"prediction", "valuation"} else "prediction"

# Valuation remote-cache strategy: local-first with optional remote fallback.
SW_HISTORY_USE_LOCAL_CACHE = os.getenv("SW_HISTORY_USE_LOCAL_CACHE", "1").lower() in {
    "1", "true", "yes", "on"
}
SW_HISTORY_USE_REMOTE_FALLBACK = os.getenv("SW_HISTORY_USE_REMOTE_FALLBACK", "1").lower() in {
    "1", "true", "yes", "on"
}
BUSINESS_MATCH_USE_REMOTE_FALLBACK = os.getenv("BUSINESS_MATCH_USE_REMOTE_FALLBACK", "1").lower() in {
    "1", "true", "yes", "on"
}

# Traditional tiered valuation template (tab-2 supplement for traditional valuation panel)
TRADITIONAL_TIER_SCHEMES = {
    "high_growth": {
        "style_label": "高增长",
        "tiers": {
            "conservative": {
                "label": "风控优先",
                "weights": {
                    "pe": 0.20,
                    "peg": 0.20,
                    "ps": 0.15,
                    "scarcity_overlay": 0.15,
                    "sw_history": 0.10,
                    "fcff_dcf": 0.10,
                    "pb": 0.08,
                    "ddm": 0.02,
                },
                "range_multiplier": (0.94, 1.04),
            },
            "balanced": {
                "label": "平衡",
                "weights": {
                    "pe": 0.28,
                    "peg": 0.24,
                    "ps": 0.16,
                    "scarcity_overlay": 0.14,
                    "sw_history": 0.08,
                    "fcff_dcf": 0.06,
                    "pb": 0.03,
                    "ddm": 0.01,
                },
                "range_multiplier": (0.95, 1.08),
            },
            "aggressive": {
                "label": "成长进攻",
                "weights": {
                    "pe": 0.35,
                    "peg": 0.28,
                    "ps": 0.16,
                    "scarcity_overlay": 0.12,
                    "sw_history": 0.06,
                    "fcff_dcf": 0.02,
                    "pb": 0.01,
                    "ddm": 0.00,
                },
                "range_multiplier": (0.95, 1.15),
            },
        },
    },
    "stable_value": {
        "style_label": "低增长稳定",
        "tiers": {
            "conservative": {
                "label": "风控优先",
                "weights": {
                    "pb": 0.30,
                    "fcff_dcf": 0.24,
                    "pe": 0.16,
                    "sw_history": 0.10,
                    "ps": 0.08,
                    "scarcity_overlay": 0.06,
                    "peg": 0.04,
                    "ddm": 0.02,
                },
                "range_multiplier": (0.96, 1.04),
            },
            "balanced": {
                "label": "平衡",
                "weights": {
                    "pb": 0.24,
                    "fcff_dcf": 0.22,
                    "pe": 0.20,
                    "sw_history": 0.12,
                    "ps": 0.10,
                    "scarcity_overlay": 0.06,
                    "peg": 0.04,
                    "ddm": 0.02,
                },
                "range_multiplier": (0.95, 1.08),
            },
            "aggressive": {
                "label": "收益增强",
                "weights": {
                    "pb": 0.18,
                    "fcff_dcf": 0.17,
                    "pe": 0.28,
                    "sw_history": 0.12,
                    "ps": 0.12,
                    "scarcity_overlay": 0.07,
                    "peg": 0.04,
                    "ddm": 0.02,
                },
                "range_multiplier": (0.94, 1.13),
            },
        },
    },
    "balanced": {
        "style_label": "均衡",
        "tiers": {
            "conservative": {
                "label": "风控优先",
                "weights": {
                    "pe": 0.23,
                    "peg": 0.18,
                    "ps": 0.14,
                    "scarcity_overlay": 0.12,
                    "sw_history": 0.12,
                    "fcff_dcf": 0.10,
                    "pb": 0.09,
                    "ddm": 0.02,
                },
                "range_multiplier": (0.95, 1.04),
            },
            "balanced": {
                "label": "平衡",
                "weights": {
                    "pe": 0.26,
                    "peg": 0.20,
                    "ps": 0.15,
                    "scarcity_overlay": 0.12,
                    "sw_history": 0.10,
                    "fcff_dcf": 0.09,
                    "pb": 0.06,
                    "ddm": 0.02,
                },
                "range_multiplier": (0.95, 1.08),
            },
            "aggressive": {
                "label": "收益增强",
                "weights": {
                    "pe": 0.31,
                    "peg": 0.24,
                    "ps": 0.15,
                    "scarcity_overlay": 0.11,
                    "sw_history": 0.08,
                    "fcff_dcf": 0.06,
                    "pb": 0.04,
                    "ddm": 0.01,
                },
                "range_multiplier": (0.95, 1.14),
            },
        },
    },
}

TRADITIONAL_STYLE_INDUSTRY_GROWTH_KEYWORDS = ["半导体", "电子", "软件", "互联网", "传媒", "生物", "医药", "军工", "通信"]
TRADITIONAL_STYLE_INDUSTRY_STABLE_KEYWORDS = ["银行", "保险", "公用", "煤炭", "钢铁", "交运", "地产"]

TRADITIONAL_STYLE_SCORE_RULES = {
    "industry_growth_bias": 1.15,
    "industry_stable_bias": -0.9,
    "roe_high_threshold": 20.0,
    "roe_mid_threshold": 12.0,
    "roe_high_bonus": 0.7,
    "roe_mid_bonus": 0.35,
    "gross_margin_high_threshold": 40.0,
    "gross_margin_mid_threshold": 28.0,
    "gross_margin_high_bonus": 0.55,
    "gross_margin_mid_bonus": 0.25,
    "debt_low_threshold": 35.0,
    "debt_high_threshold": 65.0,
    "debt_low_bonus": 0.2,
    "debt_high_penalty": -0.2,
    "peg_available_bonus": 0.25,
    "pb_fcff_available_penalty": -0.1,
}

TRADITIONAL_STYLE_SCORE_THRESHOLDS = {
    "high_growth_min": 1.1,
    "stable_value_max": -0.35,
}

TRADITIONAL_POSITION_GUIDANCE_RULES = {
    "no_price": {
        "suggested_position_range": "30%-55%",
        "message": "当前价不可用，默认维持中性仓位。",
    },
    "below_conservative": {
        "suggested_position_range": "60%-75%",
        "message": "当前价低于风控区间下沿，可考虑分批提高仓位。",
    },
    "below_balanced": {
        "suggested_position_range": "45%-65%",
        "message": "当前价低于平衡区间，可考虑逐步加仓。",
    },
    "within_balanced": {
        "suggested_position_range": "35%-55%",
        "message": "当前价位于平衡区间，维持中性仓位。",
    },
    "within_aggressive": {
        "suggested_position_range": "25%-40%",
        "message": "当前价处于偏高区间，建议逐步降低仓位。",
    },
    "above_aggressive": {
        "suggested_position_range": "15%-30%",
        "message": "当前价高于进攻区间上沿，建议偏防守仓位。",
    },
    "volatility_thresholds": {
        "low_max": 0.03,
        "high_min": 0.06,
    },
    "style_volatility_layers": {
        "high_growth": {
            "low": {
                "below_conservative": {
                    "suggested_position_range": "60%-78%",
                    "message": "高增长且波动较低，偏进攻但保留安全垫。",
                },
                "below_balanced": {
                    "suggested_position_range": "48%-68%",
                    "message": "高增长且波动较低，适合逐步加仓。",
                },
                "within_balanced": {
                    "suggested_position_range": "38%-58%",
                    "message": "高增长且波动较低，维持中性偏多仓位。",
                },
                "within_aggressive": {
                    "suggested_position_range": "26%-42%",
                    "message": "高增长且波动较低，接近目标区间上沿，可控仓观察。",
                },
                "above_aggressive": {
                    "suggested_position_range": "18%-30%",
                    "message": "高增长但价格已偏高，建议降低追高仓位。",
                },
            },
            "medium": {
                "below_conservative": {
                    "suggested_position_range": "58%-75%",
                    "message": "高增长、波动中等，适合分批加仓。",
                },
                "below_balanced": {
                    "suggested_position_range": "45%-65%",
                    "message": "高增长、波动中等，按节奏提高仓位。",
                },
                "within_balanced": {
                    "suggested_position_range": "35%-55%",
                    "message": "高增长、波动中等，维持核心仓位。",
                },
                "within_aggressive": {
                    "suggested_position_range": "24%-38%",
                    "message": "高增长、波动中等，接近进攻上沿，仓位宜收敛。",
                },
                "above_aggressive": {
                    "suggested_position_range": "15%-28%",
                    "message": "高增长但波动已放大，建议偏防守。",
                },
            },
            "high": {
                "below_conservative": {
                    "suggested_position_range": "52%-68%",
                    "message": "高增长但波动偏高，建议偏保守分批。",
                },
                "below_balanced": {
                    "suggested_position_range": "40%-58%",
                    "message": "高增长但波动偏高，建议保留机动仓。",
                },
                "within_balanced": {
                    "suggested_position_range": "30%-48%",
                    "message": "高增长但波动偏高，建议以中低仓位持有。",
                },
                "within_aggressive": {
                    "suggested_position_range": "20%-35%",
                    "message": "高增长但波动偏高，建议逐步降仓。",
                },
                "above_aggressive": {
                    "suggested_position_range": "12%-25%",
                    "message": "高增长且波动偏高，建议严格防守。",
                },
            },
        },
        "stable_value": {
            "low": {
                "below_conservative": {
                    "suggested_position_range": "62%-82%",
                    "message": "低增长稳定且波动较低，可适度提高底仓。",
                },
                "below_balanced": {
                    "suggested_position_range": "50%-70%",
                    "message": "低增长稳定且波动较低，适合稳步加仓。",
                },
                "within_balanced": {
                    "suggested_position_range": "40%-60%",
                    "message": "低增长稳定且波动较低，宜维持均衡仓位。",
                },
                "within_aggressive": {
                    "suggested_position_range": "28%-42%",
                    "message": "低增长稳定但价格偏高，可适度减仓。",
                },
                "above_aggressive": {
                    "suggested_position_range": "18%-30%",
                    "message": "低增长稳定但价格已偏高，建议偏防守。",
                },
            },
            "medium": {
                "below_conservative": {
                    "suggested_position_range": "58%-76%",
                    "message": "低增长稳定、波动中等，建议分批提高仓位。",
                },
                "below_balanced": {
                    "suggested_position_range": "46%-66%",
                    "message": "低增长稳定、波动中等，适合逐步加仓。",
                },
                "within_balanced": {
                    "suggested_position_range": "36%-56%",
                    "message": "低增长稳定、波动中等，维持中性仓位。",
                },
                "within_aggressive": {
                    "suggested_position_range": "26%-40%",
                    "message": "低增长稳定、波动中等，逐步降低仓位。",
                },
                "above_aggressive": {
                    "suggested_position_range": "16%-28%",
                    "message": "低增长稳定但价格偏高，建议偏防守。",
                },
            },
            "high": {
                "below_conservative": {
                    "suggested_position_range": "54%-70%",
                    "message": "低增长稳定但波动偏高，建议保守加仓。",
                },
                "below_balanced": {
                    "suggested_position_range": "42%-60%",
                    "message": "低增长稳定但波动偏高，建议保持机动性。",
                },
                "within_balanced": {
                    "suggested_position_range": "32%-48%",
                    "message": "低增长稳定但波动偏高，建议低中仓位持有。",
                },
                "within_aggressive": {
                    "suggested_position_range": "22%-36%",
                    "message": "低增长稳定但波动偏高，建议收敛仓位。",
                },
                "above_aggressive": {
                    "suggested_position_range": "12%-24%",
                    "message": "低增长稳定且波动偏高，建议严格防守。",
                },
            },
        },
        "balanced": {
            "low": {
                "below_conservative": {
                    "suggested_position_range": "60%-77%",
                    "message": "均衡风格且波动较低，可适度提高仓位。",
                },
                "below_balanced": {
                    "suggested_position_range": "48%-67%",
                    "message": "均衡风格且波动较低，适合分批加仓。",
                },
                "within_balanced": {
                    "suggested_position_range": "38%-58%",
                    "message": "均衡风格且波动较低，维持均衡仓位。",
                },
                "within_aggressive": {
                    "suggested_position_range": "26%-40%",
                    "message": "均衡风格且波动较低，接近上沿，可适度降仓。",
                },
                "above_aggressive": {
                    "suggested_position_range": "16%-28%",
                    "message": "均衡风格但价格偏高，建议防守。",
                },
            },
            "medium": {
                "below_conservative": {
                    "suggested_position_range": "58%-74%",
                    "message": "均衡风格、波动中等，建议分批提高仓位。",
                },
                "below_balanced": {
                    "suggested_position_range": "45%-64%",
                    "message": "均衡风格、波动中等，适合逐步加仓。",
                },
                "within_balanced": {
                    "suggested_position_range": "35%-55%",
                    "message": "均衡风格、波动中等，维持中性仓位。",
                },
                "within_aggressive": {
                    "suggested_position_range": "25%-38%",
                    "message": "均衡风格、波动中等，建议收敛仓位。",
                },
                "above_aggressive": {
                    "suggested_position_range": "15%-26%",
                    "message": "均衡风格但价格偏高，建议偏防守。",
                },
            },
            "high": {
                "below_conservative": {
                    "suggested_position_range": "54%-70%",
                    "message": "均衡风格但波动偏高，建议保守加仓。",
                },
                "below_balanced": {
                    "suggested_position_range": "42%-60%",
                    "message": "均衡风格但波动偏高，建议保持机动性。",
                },
                "within_balanced": {
                    "suggested_position_range": "32%-48%",
                    "message": "均衡风格但波动偏高，建议中低仓位持有。",
                },
                "within_aggressive": {
                    "suggested_position_range": "22%-35%",
                    "message": "均衡风格但波动偏高，建议逐步降仓。",
                },
                "above_aggressive": {
                    "suggested_position_range": "12%-24%",
                    "message": "均衡风格且波动偏高，建议防守。",
                },
            },
        },
    },
    "summary_templates": {
        "default": "{style_label} | {volatility_label} | {state_label} | 仓位 {suggested_position_range}",
        "holding": "{style_label}风格、{volatility_label}、{state_label}，建议仓位 {suggested_position_range}；{message}",
    },
}

