# Generated by Django 5.2.4 on 2025-08-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockdata', '0005_corporationbasic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTopBottomQuantile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_index=True, max_length=10, verbose_name='交易代码')),
                ('freq', models.CharField(default='D', max_length=5, verbose_name='交易周期')),
                ('quantile', models.FloatField(blank=True, null=True, verbose_name='分位数')),
                ('pct_gain_1p', models.FloatField(blank=True, null=True, verbose_name='1个周期涨幅')),
                ('pct_gain_2p', models.FloatField(blank=True, null=True, verbose_name='2个周期涨幅')),
                ('pct_gain_3p', models.FloatField(blank=True, null=True, verbose_name='3个周期涨幅')),
                ('pct_gain_5p', models.FloatField(blank=True, null=True, verbose_name='5个周期涨幅')),
                ('pct_loss_1p', models.FloatField(blank=True, null=True, verbose_name='1个周期跌幅')),
                ('pct_loss_2p', models.FloatField(blank=True, null=True, verbose_name='2个周期跌幅')),
                ('pct_loss_3p', models.FloatField(blank=True, null=True, verbose_name='3个周期跌幅')),
                ('pct_loss_5p', models.FloatField(blank=True, null=True, verbose_name='5个周期跌幅')),
                ('top_or_bottom', models.CharField(blank=True, default='B', max_length=1, null=True, verbose_name='顶底')),
                ('period', models.IntegerField(blank=True, default=34, null=True, verbose_name='一个周期跨度')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_bottom_quantile', to='stockdata.corporation')),
            ],
            options={
                'verbose_name': '分位数高低点',
                'verbose_name_plural': '分位数高低点',
                'ordering': ['ts_code'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='StockTopBottomHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_index=True, max_length=10, verbose_name='交易代码')),
                ('trade_date', models.DateField(verbose_name='交易日')),
                ('freq', models.CharField(default='D', max_length=5, verbose_name='周期')),
                ('asset', models.CharField(default='E', max_length=1, verbose_name='股票或指数')),
                ('period', models.IntegerField(blank=True, default=34, null=True, verbose_name='一个周期长度')),
                ('pct_gain_1p', models.FloatField(blank=True, null=True, verbose_name='一个周期涨幅')),
                ('pct_gain_1p_date', models.DateField(blank=True, null=True, verbose_name='一个周期涨幅匹配日期')),
                ('pct_gain_2p', models.FloatField(blank=True, null=True, verbose_name='两个周期涨幅')),
                ('pct_gain_2p_date', models.DateField(blank=True, null=True, verbose_name='两个周期涨幅匹配日期')),
                ('pct_gain_3p', models.FloatField(blank=True, null=True, verbose_name='三个周期涨幅')),
                ('pct_gain_3p_date', models.DateField(blank=True, null=True, verbose_name='三个周期涨幅匹配日期')),
                ('pct_gain_5p', models.FloatField(blank=True, null=True, verbose_name='五个周期涨幅')),
                ('pct_gain_5p_date', models.DateField(blank=True, null=True, verbose_name='五个周期涨幅匹配日期')),
                ('pct_loss_1p', models.FloatField(blank=True, null=True, verbose_name='一个周期跌幅')),
                ('pct_loss_1p_date', models.DateField(blank=True, null=True, verbose_name='一个周期跌幅匹配日期')),
                ('pct_loss_2p', models.FloatField(blank=True, null=True, verbose_name='两个周期跌幅')),
                ('pct_loss_2p_date', models.DateField(blank=True, null=True, verbose_name='两个周期跌幅匹配日期')),
                ('pct_loss_3p', models.FloatField(blank=True, null=True, verbose_name='三个周期跌幅')),
                ('pct_loss_3p_date', models.DateField(blank=True, null=True, verbose_name='三个周期跌幅匹配日期')),
                ('pct_loss_5p', models.FloatField(blank=True, null=True, verbose_name='五个周期跌幅')),
                ('pct_loss_5p_date', models.DateField(blank=True, null=True, verbose_name='五个周期跌幅匹配日期')),
                ('top_or_bottom', models.CharField(blank=True, default='N', max_length=1, null=True, verbose_name='scipy峰谷')),
                ('top_or_bottom_optimized', models.CharField(blank=True, max_length=25, null=True, verbose_name='优化校验峰谷')),
                ('top_or_bottom_stat', models.CharField(blank=True, max_length=1, null=True, verbose_name='统计峰谷')),
                ('top_or_bottom_stat_optimized', models.CharField(blank=True, max_length=25, null=True, verbose_name='优化统计峰谷')),
                ('top_bottom_volatility_stat', models.CharField(blank=True, max_length=1, null=True, verbose_name='统计涨跌幅大的峰谷')),
                ('top_bottom_volatility_optimized', models.CharField(blank=True, max_length=25, null=True, verbose_name='优化的涨跌幅大的峰谷')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_bottom', to='stockdata.corporation')),
            ],
            options={
                'verbose_name': '历史高低点',
                'verbose_name_plural': '历史高低点',
                'ordering': ['trade_date'],
                'get_latest_by': 'id',
                'unique_together': {('trade_date', 'ts_code', 'freq')},
            },
        ),
    ]
