# Generated by Django 5.2.4 on 2025-08-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('stockdata', '0005_corporationbasic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockTopBottomQuantile',
            new_name='StockGainLossQuantile',
        ),
    ]
