# Generated by Django 5.2.4 on 2025-08-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_stocktopbottomhistory_period'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocktopbottomhistory',
            unique_together={('trade_date', 'ts_code', 'freq', 'top_or_bottom')},
        ),
    ]
