# Generated by Django 5.2.4 on 2025-08-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_stocktopbottomhistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktopbottomhistory',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘价'),
        ),
    ]
