# Generated by Django 5.2.4 on 2025-09-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_stocktopbottomhistory_close'),
        ('stockdata', '0006_alter_stockfundamentalhistory_pb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockgainlossquantile',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_gain_loss_quantiles', to='stockdata.corporation'),
        ),
    ]
