from datetime import date


PUBLIC_API_GROUPS = [
    {
        'key': 'market_data',
        'name': 'Market Data',
        'endpoints': [
            {
                'id': 'market_data.securities.list',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities',
                'name': '证券主数据列表',
                'description': '按条件查询已持久化的证券主数据。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'asset_type', 'in': 'query', 'type': 'string', 'required': False, 'example': 'stock'},
                    {'name': 'market', 'in': 'query', 'type': 'string', 'required': False, 'example': '主板'},
                    {'name': 'industry', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'list_status', 'in': 'query', 'type': 'string', 'required': False, 'example': 'L'},
                    {'name': 'q', 'in': 'query', 'type': 'string', 'required': False, 'example': '平安'},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200},
                'response_example': {'ts_code': '000001.SZ', 'name': '平安银行'},
            },
            {
                'id': 'market_data.securities.detail',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code',
                'name': '证券详情和分类身份',
                'description': '查询单个证券的规范代码、分类和基础身份信息。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                ],
                'response_example': {'ts_code': '000001.SZ', 'symbol': '000001'},
            },
            {
                'id': 'market_data.securities.bars',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/bars',
                'name': 'EOD 行情历史',
                'description': '查询有界的证券日行情历史。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': True, 'example': '2026-09-01'},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': True, 'example': '2026-09-10'},
                    {'name': 'adjust', 'in': 'query', 'type': 'string', 'required': False, 'default': 'qfq', 'enum': ['raw', 'qfq', 'hfq']},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366},
                'response_example': {'trade_date': '2026-09-10', 'close': 10.2},
            },
            {
                'id': 'market_data.securities.fundamentals',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/fundamentals',
                'name': '日基本面历史',
                'description': '查询有界的证券日基本面历史。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': True, 'example': '2026-09-01'},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': True, 'example': '2026-09-10'},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366},
                'response_example': {'trade_date': '2026-09-10', 'pe': 12.5},
            },
            {
                'id': 'market_data.regime.market',
                'method': 'GET',
                'path': '/api/v1/market-analysis/market/regime',
                'name': '市场风格状态',
                'description': '查询指定日期和基准下的市场风格状态。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-09-10'},
                    {'name': 'benchmark_ts_code', 'in': 'query', 'type': 'string', 'required': False, 'default': '000001.SH'},
                ],
                'response_example': {'regime': 'neutral', 'source': 'persisted'},
            },
            {
                'id': 'market_data.regime.security',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/regime',
                'name': '个股风格状态',
                'description': '查询指定证券在某个 as-of 日期的风格状态。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-09-10'},
                ],
                'response_example': {'regime': 'neutral', 'source': 'persisted'},
            },
        ],
    },
    {
        'key': 'financials',
        'name': 'Financials',
        'endpoints': [
            {
                'id': 'financials.securities.records',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/financials',
                'name': '财务报表和指标',
                'description': '查询经过 as-of 过滤的已持久化财务记录。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'dataset', 'in': 'query', 'type': 'string', 'required': True, 'enum': ['income', 'balance_sheet', 'cashflow', 'indicator', 'forecast', 'express', 'dividend', 'audit', 'main_business']},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-09-10'},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-06-30'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-01-01'},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366},
                'response_example': {'ts_code': '000001.SZ', 'dataset': 'income', 'effective_date': '2026-08-30'},
            },
            {
                'id': 'financials.securities.disclosures',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/disclosures',
                'name': '财务披露日历',
                'description': '查询经过 as-of 过滤的披露日程和公开日期 provenance。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-09-10'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-01-01'},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-09-10'},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366},
                'response_example': {'ts_code': '000001.SZ', 'effective_date': '2026-08-30', 'actual_date': '2026-08-30'},
            },
        ],
    },
    {
        'key': 'traditional_valuation',
        'name': 'Traditional Valuation',
        'endpoints': [
            {
                'id': 'traditional_valuation.current',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/valuations/traditional',
                'name': '传统估值当前快照',
                'description': '查询已发布的传统估值当前快照、摘要和风险结果。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-09-10'},
                    {'name': 'report_type', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['Q1', 'H1', 'Q3', 'FY']},
                    {'name': 'financial_end_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-06-30'},
                    {'name': 'profit_bucket', 'in': 'query', 'type': 'string', 'required': False, 'default': 'formal', 'enum': ['formal', 'blended']},
                    {'name': 'variant', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'style_profile', 'in': 'query', 'type': 'string', 'required': False, 'default': 'baseline'},
                    {'name': 'include_methods', 'in': 'query', 'type': 'boolean', 'required': False, 'default': False, 'requires_scope': 'valuation:diagnostics_read'},
                    {'name': 'include_variants', 'in': 'query', 'type': 'boolean', 'required': False, 'default': False, 'requires_scope': 'valuation:diagnostics_read'},
                    {'name': 'include_risk', 'in': 'query', 'type': 'boolean', 'required': False, 'default': True},
                ],
                'response_example': {'ts_code': '000001.SZ', 'valuation_variant': 'sw_l3_baseline', 'summary': {}},
            },
            {
                'id': 'traditional_valuation.history',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/valuations/traditional/history',
                'name': '传统估值历史',
                'description': '查询有界的传统估值历史快照。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': True, 'example': '2026-01-01'},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': True, 'example': '2026-09-10'},
                    {'name': 'report_type', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['Q1', 'H1', 'Q3', 'FY']},
                    {'name': 'profit_bucket', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['formal', 'blended']},
                    {'name': 'variant', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'style_profile', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                    {'name': 'include_diagnostics', 'in': 'query', 'type': 'boolean', 'required': False, 'default': False, 'requires_scope': 'valuation:diagnostics_read'},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366, 'max_rows': 2000},
                'response_example': {'snapshot_id': 1, 'report_type': 'H1', 'summary': {}},
            },
            {
                'id': 'traditional_valuation.compare',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/valuations/traditional/compare',
                'name': '传统估值多变体比较',
                'description': '查询已发布的传统估值行业变体和 active variant。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False, 'example': '2026-09-10'},
                    {'name': 'report_type', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['Q1', 'H1', 'Q3', 'FY']},
                    {'name': 'financial_end_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'profit_bucket', 'in': 'query', 'type': 'string', 'required': False, 'default': 'formal', 'enum': ['formal', 'blended']},
                    {'name': 'style_profile', 'in': 'query', 'type': 'string', 'required': False, 'default': 'baseline'},
                    {'name': 'variant', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'limit', 'in': 'query', 'type': 'integer', 'required': False, 'default': 10, 'maximum': 20},
                    {'name': 'include_methods', 'in': 'query', 'type': 'boolean', 'required': False, 'default': False, 'requires_scope': 'valuation:diagnostics_read'},
                    {'name': 'include_diagnostics', 'in': 'query', 'type': 'boolean', 'required': False, 'default': False, 'requires_scope': 'valuation:diagnostics_read'},
                ],
                'limits': {'limit_default': 10, 'limit_max': 20},
                'response_example': {'active_variant': 'sw_l3_baseline', 'variants': []},
            },
        ],
    },
    {
        'key': 'indices',
        'name': 'Indices',
        'endpoints': [
            {
                'id': 'indices.catalog',
                'method': 'GET',
                'path': '/api/v1/market-analysis/indices/catalog',
                'name': '指数目录',
                'description': '查询固定指数池、支持指标和数据新鲜度。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'index_keys', 'in': 'query', 'type': 'string', 'required': False, 'example': 'sh,hs300'},
                ],
                'response_example': {'index_key': 'hs300', 'ts_code': '399300.SZ', 'data_status': 'VALID'},
            },
            {
                'id': 'indices.valuation',
                'method': 'GET',
                'path': '/api/v1/market-analysis/indices/:index_key/valuation',
                'name': '指数估值和历史分位',
                'description': '查询单指数当前估值和指定指标的历史分位。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'index_key', 'in': 'path', 'type': 'string', 'required': True, 'example': 'hs300'},
                    {'name': 'metric', 'in': 'query', 'type': 'string', 'required': True, 'enum': ['PE', 'PETTM', 'PB']},
                    {'name': 'window', 'in': 'query', 'type': 'string', 'required': False, 'default': 'ALL'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'band_pct', 'in': 'query', 'type': 'number', 'required': False, 'default': 0.1},
                ],
                'response_example': {'index_key': 'hs300', 'metric': 'PE', 'method': {}},
            },
            {
                'id': 'indices.health',
                'method': 'GET',
                'path': '/api/v1/market-analysis/indices/health',
                'name': '市场健康度',
                'description': '查询市场健康度和估值温度。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'style', 'in': 'query', 'type': 'string', 'required': False, 'default': 'overall'},
                    {'name': 'calculation_version', 'in': 'query', 'type': 'string', 'required': False},
                ],
            },
            {
                'id': 'indices.equity_bond',
                'method': 'GET',
                'path': '/api/v1/market-analysis/indices/equity-bond',
                'name': '股债性价比',
                'description': '查询股息率、国债收益率和利差。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'index_key', 'in': 'query', 'type': 'string', 'required': False, 'default': 'hs300'},
                    {'name': 'window', 'in': 'query', 'type': 'string', 'required': False, 'default': '5Y'},
                ],
            },
            {
                'id': 'indices.health_history',
                'method': 'GET',
                'path': '/api/v1/market-analysis/indices/health/history',
                'name': '历史健康度',
                'description': '查询有界的历史健康度序列。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'window', 'in': 'query', 'type': 'string', 'required': False, 'default': '5Y'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_rows': 2000},
            },
            {
                'id': 'indices.health_events',
                'method': 'GET',
                'path': '/api/v1/market-analysis/indices/health/events',
                'name': '健康度关键事件',
                'description': '查询有界的估值和健康度关键事件。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'event_type', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_rows': 2000},
            },
        ],
    },
    {
        'key': 'market_sentiment',
        'name': 'Market Sentiment',
        'endpoints': [
            {
                'id': 'market_sentiment.market',
                'method': 'GET',
                'path': '/api/v1/market-analysis/sentiment/market',
                'name': '市场情绪快照',
                'description': '查询指定日期的市场 EOD 情绪快照。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'engine_version', 'in': 'query', 'type': 'string', 'required': False},
                ],
            },
            {
                'id': 'market_sentiment.market_history',
                'method': 'GET',
                'path': '/api/v1/market-analysis/sentiment/market/history',
                'name': '市场情绪历史',
                'description': '查询有界的市场 EOD 情绪历史序列。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': True},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': True},
                    {'name': 'engine_version', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366, 'max_rows': 2000},
            },
            {
                'id': 'market_sentiment.stock',
                'method': 'GET',
                'path': '/api/v1/market-analysis/sentiment/stocks/:ts_code',
                'name': '个股情绪快照',
                'description': '查询指定股票的 EOD 情绪快照。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'engine_version', 'in': 'query', 'type': 'string', 'required': False},
                ],
            },
            {
                'id': 'market_sentiment.stock_history',
                'method': 'GET',
                'path': '/api/v1/market-analysis/sentiment/stocks/:ts_code/history',
                'name': '个股情绪历史',
                'description': '查询有界的个股 EOD 情绪历史序列。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': True},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': True},
                    {'name': 'engine_version', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366, 'max_rows': 2000},
            },
            {
                'id': 'market_sentiment.stock_ranking',
                'method': 'GET',
                'path': '/api/v1/market-analysis/sentiment/stocks/ranking',
                'name': '个股情绪排名',
                'description': '查询指定交易日的个股情绪排名。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'engine_version', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'status', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200},
            },
        ],
    },
    {
        'key': 'predictive_valuation',
        'name': 'Predictive Valuation',
        'endpoints': [
            {
                'id': 'predictive_valuation.current',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/valuations/predictive',
                'name': '预测估值当前快照',
                'description': '查询已持久化的预测估值当前结果和目标范围。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'report_type', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['Q1', 'H1', 'Q3', 'FY', 'FUSION', 'LATEST']},
                    {'name': 'anchor_mode', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['ann', 'live_latest']},
                    {'name': 'model_version', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'serving_slot', 'in': 'query', 'type': 'string', 'required': False, 'default': 'production'},
                ],
                'response_example': {'ts_code': '000001.SZ', 'report_type': 'H1', 'data_status': 'COMPLETE'},
            },
            {
                'id': 'predictive_valuation.history',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/valuations/predictive/history',
                'name': '预测估值历史',
                'description': '查询有界的预测估值历史快照。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'start_date', 'in': 'query', 'type': 'date', 'required': True},
                    {'name': 'end_date', 'in': 'query', 'type': 'date', 'required': True},
                    {'name': 'report_type', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['Q1', 'H1', 'Q3', 'FY', 'FUSION']},
                    {'name': 'page', 'in': 'query', 'type': 'integer', 'required': False, 'default': 1},
                    {'name': 'page_size', 'in': 'query', 'type': 'integer', 'required': False, 'default': 50},
                ],
                'limits': {'page_size_default': 50, 'page_size_max': 200, 'max_date_range_days': 366, 'max_rows': 2000},
            },
            {
                'id': 'predictive_valuation.fusion',
                'method': 'GET',
                'path': '/api/v1/market-analysis/securities/:ts_code/valuations/predictive/fusion',
                'name': '预测估值季度融合',
                'description': '查询已持久化的 Q1/H1/Q3/FY 融合结果。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'ts_code', 'in': 'path', 'type': 'string', 'required': True, 'example': '000001.SZ'},
                    {'name': 'asof_date', 'in': 'query', 'type': 'date', 'required': False},
                    {'name': 'anchor_mode', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['ann', 'live_latest']},
                    {'name': 'model_version', 'in': 'query', 'type': 'string', 'required': False},
                ],
            },
            {
                'id': 'predictive_valuation.status',
                'method': 'GET',
                'path': '/api/v1/market-analysis/valuations/predictive/status',
                'name': '预测估值服务状态',
                'description': '查询预测模型、快照和特征数据可用性。',
                'visibility': 'public',
                'access_mode': 'authenticated',
                'parameters': [
                    {'name': 'report_type', 'in': 'query', 'type': 'string', 'required': False, 'enum': ['Q1', 'H1', 'Q3', 'FY']},
                    {'name': 'model_version', 'in': 'query', 'type': 'string', 'required': False},
                    {'name': 'serving_slot', 'in': 'query', 'type': 'string', 'required': False, 'default': 'production'},
                ],
            },
        ],
    },
]


def public_api_catalog():
    return {
        'catalog_version': date.today().isoformat(),
        'groups': PUBLIC_API_GROUPS,
    }
